// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"math"

	"github.com/jinzhu/copier"
	"gorm.io/gorm"
)

var (
	_ sql.IsolationLevel
)

type (
	cmsSubjectModel interface {
		Insert(ctx context.Context, data *CmsSubject) error
		FindOne(ctx context.Context, id int64, preloadList ...string) (*CmsSubject, error)
		OrmSession(ctx context.Context) *gorm.DB
		Transaction(ctx context.Context, fc func(tx *gorm.DB) error, opts ...*sql.TxOptions) error
		FindPageListByBuilder(ormSession *gorm.DB, page, pageSize int64) (*CmsSubjectPagination, error)
		Update(ctx context.Context, data *CmsSubject) error
		Delete(ctx context.Context, id int64) error
	}

	defaultCmsSubjectModel struct {
		table   string
		ormConn *gorm.DB
	}

	CmsSubject struct {
		Id              int64          `json:"id" gorm:"primary_key"`
		CategoryId      sql.NullInt64  `json:"category_id"`
		Title           sql.NullString `json:"title"`
		Pic             sql.NullString `json:"pic"`           // 专题主图
		ProductCount    sql.NullInt64  `json:"product_count"` // 关联产品数量
		RecommendStatus sql.NullInt64  `json:"recommend_status"`
		CreateTime      sql.NullTime   `json:"create_time"`
		CollectCount    sql.NullInt64  `json:"collect_count"`
		ReadCount       sql.NullInt64  `json:"read_count"`
		CommentCount    sql.NullInt64  `json:"comment_count"`
		AlbumPics       sql.NullString `json:"album_pics"` // 画册图片用逗号分割
		Description     sql.NullString `json:"description"`
		ShowStatus      sql.NullInt64  `json:"show_status"` // 显示状态：0->不显示；1->显示
		Content         sql.NullString `json:"content"`
		ForwardCount    sql.NullInt64  `json:"forward_count"` // 转发数
		CategoryName    sql.NullString `json:"category_name"` // 专题分类名称
		CmsSubjectRelation
	}

	CmsSubjectPagination struct {
		Data []*CmsSubject
		CmsSubjectPaginationBasic
	}

	CmsSubjectPaginationBasic struct {
		CurrentPage int64
		PageSize    int64
		TotalCount  int64
		TotalPage   int64
	}
)

func newCmsSubjectModel(db *gorm.DB) *defaultCmsSubjectModel {
	return &defaultCmsSubjectModel{
		table:   "`cms_subject`",
		ormConn: db,
	}
}

func (CmsSubject) TableName() string {
	return "`cms_subject`"
}

func (m CmsSubject) ToProto(toValue interface{}) error {
	return copier.Copy(toValue, &m)
}

func (m *defaultCmsSubjectModel) Delete(ctx context.Context, id int64) error {
	return m.OrmSession(ctx).Delete(&CmsSubject{}, id).Error
}

func (m *defaultCmsSubjectModel) FindOne(ctx context.Context, id int64, preloadList ...string) (*CmsSubject, error) {
	var mm CmsSubject
	db := m.OrmSession(ctx)
	for _, preload := range preloadList {
		db = db.Preload(preload)
	}
	err := db.First(&mm, id).Error
	switch err {
	case nil:
		return &mm, nil
	case gorm.ErrRecordNotFound:
		return nil, gorm.ErrRecordNotFound
	default:
		return nil, err
	}
}

func (m *defaultCmsSubjectModel) OrmSession(ctx context.Context) *gorm.DB {
	return m.ormConn.Model(&CmsSubject{}).WithContext(ctx)
}

func (m *defaultCmsSubjectModel) Transaction(ctx context.Context, fc func(tx *gorm.DB) error, opts ...*sql.TxOptions) error {
	return m.ormConn.WithContext(ctx).Transaction(fc, opts...)
}

func (m *defaultCmsSubjectModel) FindPageListByBuilder(db *gorm.DB, page, pageSize int64) (*CmsSubjectPagination, error) {
	// 总行数
	var totalCount int64
	if err := db.Count(&totalCount).Error; err != nil {
		return nil, err
	}
	// 总页数
	totalPage := int64(math.Ceil(float64(totalCount) / float64(pageSize)))

	resp := new(CmsSubjectPagination)
	resp.PageSize = pageSize
	resp.TotalPage = totalPage
	resp.CurrentPage = page
	resp.TotalCount = totalCount

	// 没有数据则返回空数据
	if totalCount <= 0 {
		return resp, nil
	}
	// 当前页数没有数据也返回空数据
	if totalCount < ((page - 1) * pageSize) {
		return resp, nil
	}

	offset := int((page - 1) * pageSize)
	if err := db.Offset(offset).Limit(int(pageSize)).Find(&resp.Data).Error; err != nil {
		return nil, err
	}

	return resp, nil
}

func (m CmsSubjectPagination) Pagination() CmsSubjectPaginationBasic {
	return CmsSubjectPaginationBasic{
		CurrentPage: m.CurrentPage,
		PageSize:    m.PageSize,
		TotalPage:   m.TotalPage,
		TotalCount:  m.TotalCount,
	}
}

func (m CmsSubjectPagination) ToProto(to any, toData any, toPagination any) error {
	if to != nil {
		if err := copier.CopyWithOption(to, m, copier.Option{}); err != nil {
			return err
		}
	}
	if toData != nil {
		if err := copier.Copy(toData, m.Data); err != nil {
			return err
		}
	}
	if toPagination != nil {
		if err := copier.Copy(toPagination, m.Pagination()); err != nil {
			return err
		}
	}
	return nil
}

func (m *defaultCmsSubjectModel) Insert(ctx context.Context, data *CmsSubject) error {
	return m.OrmSession(ctx).Create(data).Error
}

func (m *defaultCmsSubjectModel) Update(ctx context.Context, data *CmsSubject) error {
	if data.Id <= 0 {
		return gorm.ErrMissingWhereClause
	}
	return m.OrmSession(ctx).Where("id = ?", data.Id).Save(data).Error
}
