// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"math"

	"fmt"
	"github.com/jinzhu/copier"
	"gorm.io/gorm"
)

var (
	_ sql.IsolationLevel
)

type (
	cmsPrefrenceAreaModel interface {
		Insert(ctx context.Context, data *CmsPrefrenceArea) error
		FindOne(ctx context.Context, id int64, preloadList ...string) (*CmsPrefrenceArea, error)
		OrmSession(ctx context.Context) *gorm.DB
		Transaction(ctx context.Context, fc func(tx *gorm.DB) error, opts ...*sql.TxOptions) error
		FindPageListByBuilder(ormSession *gorm.DB, keyword *KeywordCmsPrefrenceAreaModel) (*CmsPrefrenceAreaPagination, error)
		Update(ctx context.Context, data *CmsPrefrenceArea) error
		Delete(ctx context.Context, id int64) error
	}

	defaultCmsPrefrenceAreaModel struct {
		table   string
		ormConn *gorm.DB
	}

	CmsPrefrenceArea struct {
		Id         int64          `json:"id" gorm:"primary_key"`
		Name       sql.NullString `json:"name"`
		SubTitle   sql.NullString `json:"sub_title"`
		Pic        sql.NullString `json:"pic"` // 展示图片
		Sort       sql.NullInt64  `json:"sort"`
		ShowStatus sql.NullInt64  `json:"show_status"`
		CmsPrefrenceAreaRelation
	}

	CmsPrefrenceAreaPagination struct {
		Data []*CmsPrefrenceArea
		CmsPrefrenceAreaPaginationBasic
	}

	CmsPrefrenceAreaPaginationBasic struct {
		CurrentPage int64
		PageSize    int64
		TotalCount  int64
		TotalPage   int64
	}

	KeywordCmsPrefrenceAreaModel struct {
		KeywordKey     string //like 关键字
		KeywordValue   string //like 值
		Page, PageSize int64
	}
)

func newCmsPrefrenceAreaModel(db *gorm.DB) *defaultCmsPrefrenceAreaModel {
	return &defaultCmsPrefrenceAreaModel{
		table:   "`cms_prefrence_area`",
		ormConn: db,
	}
}

func (CmsPrefrenceArea) TableName() string {
	return "`cms_prefrence_area`"
}

func (m CmsPrefrenceArea) ToProto(toValue interface{}) error {
	return copier.Copy(toValue, &m)
}

func (m *defaultCmsPrefrenceAreaModel) Delete(ctx context.Context, id int64) error {
	return m.OrmSession(ctx).Delete(&CmsPrefrenceArea{}, id).Error
}

func (m *defaultCmsPrefrenceAreaModel) FindOne(ctx context.Context, id int64, preloadList ...string) (*CmsPrefrenceArea, error) {
	var mm CmsPrefrenceArea
	db := m.OrmSession(ctx)
	for _, preload := range preloadList {
		db = db.Preload(preload)
	}
	err := db.First(&mm, id).Error
	switch err {
	case nil:
		return &mm, nil
	case gorm.ErrRecordNotFound:
		return nil, gorm.ErrRecordNotFound
	default:
		return nil, err
	}
}

func (m *defaultCmsPrefrenceAreaModel) OrmSession(ctx context.Context) *gorm.DB {
	return m.ormConn.Model(&CmsPrefrenceArea{}).WithContext(ctx)
}

func (m *defaultCmsPrefrenceAreaModel) Transaction(ctx context.Context, fc func(tx *gorm.DB) error, opts ...*sql.TxOptions) error {
	return m.ormConn.WithContext(ctx).Transaction(fc, opts...)
}

func (m *defaultCmsPrefrenceAreaModel) FindPageListByBuilder(db *gorm.DB, keyword *KeywordCmsPrefrenceAreaModel) (*CmsPrefrenceAreaPagination, error) {
	page := keyword.Page
	pageSize := keyword.PageSize
	// 总行数
	var totalCount int64
	if err := db.Count(&totalCount).Error; err != nil {
		return nil, err
	}
	// 总页数
	totalPage := int64(math.Ceil(float64(totalCount) / float64(pageSize)))

	resp := new(CmsPrefrenceAreaPagination)
	resp.PageSize = pageSize
	resp.TotalPage = totalPage
	resp.CurrentPage = page
	resp.TotalCount = totalCount

	// 没有数据则返回空数据
	if totalCount <= 0 {
		return resp, nil
	}
	// 当前页数没有数据也返回空数据
	if totalCount < ((page - 1) * pageSize) {
		return resp, nil
	}
	if keyword.KeywordKey != "" && keyword.KeywordValue != "" {
		db = db.Where(fmt.Sprintf("%s = ?", keyword.KeywordKey), keyword.KeywordValue)
	}
	offset := int((page - 1) * pageSize)
	if err := db.Offset(offset).Limit(int(pageSize)).Find(&resp.Data).Error; err != nil {
		return nil, err
	}

	return resp, nil
}

func (m CmsPrefrenceAreaPagination) Pagination() CmsPrefrenceAreaPaginationBasic {
	return CmsPrefrenceAreaPaginationBasic{
		CurrentPage: m.CurrentPage,
		PageSize:    m.PageSize,
		TotalPage:   m.TotalPage,
		TotalCount:  m.TotalCount,
	}
}

func (m CmsPrefrenceAreaPagination) ToProto(to any, toData any, toPagination any) error {
	if to != nil {
		if err := copier.CopyWithOption(to, m, copier.Option{}); err != nil {
			return err
		}
	}
	if toData != nil {
		if err := copier.Copy(toData, m.Data); err != nil {
			return err
		}
	}
	if toPagination != nil {
		if err := copier.Copy(toPagination, m.Pagination()); err != nil {
			return err
		}
	}
	return nil
}

func (m *defaultCmsPrefrenceAreaModel) Insert(ctx context.Context, data *CmsPrefrenceArea) error {
	return m.OrmSession(ctx).Create(data).Error
}

func (m *defaultCmsPrefrenceAreaModel) Update(ctx context.Context, data *CmsPrefrenceArea) error {
	if data.Id <= 0 {
		return gorm.ErrMissingWhereClause
	}
	return m.OrmSession(ctx).Where("id = ?", data.Id).Save(data).Error
}
