// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"math"

	"github.com/jinzhu/copier"
	"gorm.io/gorm"
)

var (
	_ sql.IsolationLevel
)

type (
	cmsSubjectProductRelationModel interface {
		Insert(ctx context.Context, data *CmsSubjectProductRelation) error
		FindOne(ctx context.Context, id int64, preloadList ...string) (*CmsSubjectProductRelation, error)
		OrmSession(ctx context.Context) *gorm.DB
		Transaction(ctx context.Context, fc func(tx *gorm.DB) error, opts ...*sql.TxOptions) error
		FindPageListByBuilder(ormSession *gorm.DB, keyword *KeywordCmsSubjectProductRelationModel) (*CmsSubjectProductRelationPagination, error)
		Update(ctx context.Context, data *CmsSubjectProductRelation) error
		Delete(ctx context.Context, id int64) error
	}

	defaultCmsSubjectProductRelationModel struct {
		table   string
		ormConn *gorm.DB
	}

	CmsSubjectProductRelation struct {
		Id        int64         `json:"id" gorm:"primary_key"`
		SubjectId sql.NullInt64 `json:"subject_id"`
		ProductId sql.NullInt64 `json:"product_id"`
		CmsSubjectProductRelationRelation
	}

	CmsSubjectProductRelationPagination struct {
		Data []*CmsSubjectProductRelation
		CmsSubjectProductRelationPaginationBasic
	}

	CmsSubjectProductRelationPaginationBasic struct {
		CurrentPage int64
		PageSize    int64
		TotalCount  int64
		TotalPage   int64
	}

	KeywordCmsSubjectProductRelationModel struct {
		KeywordKey     string //like 关键字
		KeywordValue   string //like 值
		Page, PageSize int64
	}
)

func newCmsSubjectProductRelationModel(db *gorm.DB) *defaultCmsSubjectProductRelationModel {
	return &defaultCmsSubjectProductRelationModel{
		table:   "`cms_subject_product_relation`",
		ormConn: db,
	}
}

func (CmsSubjectProductRelation) TableName() string {
	return "`cms_subject_product_relation`"
}

func (m CmsSubjectProductRelation) ToProto(toValue interface{}) error {
	return copier.Copy(toValue, &m)
}

func (m *defaultCmsSubjectProductRelationModel) Delete(ctx context.Context, id int64) error {
	return m.OrmSession(ctx).Delete(&CmsSubjectProductRelation{}, id).Error
}

func (m *defaultCmsSubjectProductRelationModel) FindOne(ctx context.Context, id int64, preloadList ...string) (*CmsSubjectProductRelation, error) {
	var mm CmsSubjectProductRelation
	db := m.OrmSession(ctx)
	for _, preload := range preloadList {
		db = db.Preload(preload)
	}
	err := db.First(&mm, id).Error
	switch err {
	case nil:
		return &mm, nil
	case gorm.ErrRecordNotFound:
		return nil, gorm.ErrRecordNotFound
	default:
		return nil, err
	}
}

func (m *defaultCmsSubjectProductRelationModel) OrmSession(ctx context.Context) *gorm.DB {
	return m.ormConn.Model(&CmsSubjectProductRelation{}).WithContext(ctx)
}

func (m *defaultCmsSubjectProductRelationModel) Transaction(ctx context.Context, fc func(tx *gorm.DB) error, opts ...*sql.TxOptions) error {
	return m.ormConn.WithContext(ctx).Transaction(fc, opts...)
}

func (m *defaultCmsSubjectProductRelationModel) FindPageListByBuilder(db *gorm.DB, keyword *KeywordCmsSubjectProductRelationModel) (*CmsSubjectProductRelationPagination, error) {
	page := keyword.Page
	pageSize := keyword.PageSize
	// 总行数
	var totalCount int64
	if err := db.Count(&totalCount).Error; err != nil {
		return nil, err
	}
	// 总页数
	totalPage := int64(math.Ceil(float64(totalCount) / float64(pageSize)))

	resp := new(CmsSubjectProductRelationPagination)
	resp.PageSize = pageSize
	resp.TotalPage = totalPage
	resp.CurrentPage = page
	resp.TotalCount = totalCount

	// 没有数据则返回空数据
	if totalCount <= 0 {
		return resp, nil
	}
	// 当前页数没有数据也返回空数据
	if totalCount < ((page - 1) * pageSize) {
		return resp, nil
	}
	if keyword.KeywordKey != "" && keyword.KeywordValue != "" {
		db = db.Where(fmt.Sprintf("%s = ?", keyword.KeywordKey), keyword.KeywordValue)
	}
	offset := int((page - 1) * pageSize)
	if err := db.Offset(offset).Limit(int(pageSize)).Find(&resp.Data).Error; err != nil {
		return nil, err
	}

	return resp, nil
}

func (m CmsSubjectProductRelationPagination) Pagination() CmsSubjectProductRelationPaginationBasic {
	return CmsSubjectProductRelationPaginationBasic{
		CurrentPage: m.CurrentPage,
		PageSize:    m.PageSize,
		TotalPage:   m.TotalPage,
		TotalCount:  m.TotalCount,
	}
}

func (m CmsSubjectProductRelationPagination) ToProto(to any, toData any, toPagination any) error {
	if to != nil {
		if err := copier.CopyWithOption(to, m, copier.Option{}); err != nil {
			return err
		}
	}
	if toData != nil {
		if err := copier.Copy(toData, m.Data); err != nil {
			return err
		}
	}
	if toPagination != nil {
		if err := copier.Copy(toPagination, m.Pagination()); err != nil {
			return err
		}
	}
	return nil
}

func (m *defaultCmsSubjectProductRelationModel) Insert(ctx context.Context, data *CmsSubjectProductRelation) error {
	return m.OrmSession(ctx).Create(data).Error
}

func (m *defaultCmsSubjectProductRelationModel) Update(ctx context.Context, data *CmsSubjectProductRelation) error {
	if data.Id <= 0 {
		return gorm.ErrMissingWhereClause
	}
	return m.OrmSession(ctx).Where("id = ?", data.Id).Save(data).Error
}
