// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"math"

	"github.com/jinzhu/copier"
	"gorm.io/gorm"
)

var (
	_ sql.IsolationLevel
)

type (
	cmsPrefrenceAreaProductRelationModel interface {
		Insert(ctx context.Context, data *CmsPrefrenceAreaProductRelation) error
		FindOne(ctx context.Context, id int64, preloadList ...string) (*CmsPrefrenceAreaProductRelation, error)
		OrmSession(ctx context.Context) *gorm.DB
		Transaction(ctx context.Context, fc func(tx *gorm.DB) error, opts ...*sql.TxOptions) error
		FindPageListByBuilder(ormSession *gorm.DB, page, pageSize int64) (*CmsPrefrenceAreaProductRelationPagination, error)
		Update(ctx context.Context, data *CmsPrefrenceAreaProductRelation) error
		Delete(ctx context.Context, id int64) error
	}

	defaultCmsPrefrenceAreaProductRelationModel struct {
		table   string
		ormConn *gorm.DB
	}

	CmsPrefrenceAreaProductRelation struct {
		Id              int64         `json:"id" gorm:"primary_key"`
		PrefrenceAreaId sql.NullInt64 `json:"prefrence_area_id"`
		ProductId       sql.NullInt64 `json:"product_id"`
		CmsPrefrenceAreaProductRelationRelation
	}

	CmsPrefrenceAreaProductRelationPagination struct {
		Data []*CmsPrefrenceAreaProductRelation
		CmsPrefrenceAreaProductRelationPaginationBasic
	}

	CmsPrefrenceAreaProductRelationPaginationBasic struct {
		CurrentPage int64
		PageSize    int64
		TotalCount  int64
		TotalPage   int64
	}
)

func newCmsPrefrenceAreaProductRelationModel(db *gorm.DB) *defaultCmsPrefrenceAreaProductRelationModel {
	return &defaultCmsPrefrenceAreaProductRelationModel{
		table:   "`cms_prefrence_area_product_relation`",
		ormConn: db,
	}
}

func (CmsPrefrenceAreaProductRelation) TableName() string {
	return "`cms_prefrence_area_product_relation`"
}

func (m CmsPrefrenceAreaProductRelation) ToProto(toValue interface{}) error {
	return copier.Copy(toValue, &m)
}

func (m *defaultCmsPrefrenceAreaProductRelationModel) Delete(ctx context.Context, id int64) error {
	return m.OrmSession(ctx).Delete(&CmsPrefrenceAreaProductRelation{}, id).Error
}

func (m *defaultCmsPrefrenceAreaProductRelationModel) FindOne(ctx context.Context, id int64, preloadList ...string) (*CmsPrefrenceAreaProductRelation, error) {
	var mm CmsPrefrenceAreaProductRelation
	db := m.OrmSession(ctx)
	for _, preload := range preloadList {
		db = db.Preload(preload)
	}
	err := db.First(&mm, id).Error
	switch err {
	case nil:
		return &mm, nil
	case gorm.ErrRecordNotFound:
		return nil, gorm.ErrRecordNotFound
	default:
		return nil, err
	}
}

func (m *defaultCmsPrefrenceAreaProductRelationModel) OrmSession(ctx context.Context) *gorm.DB {
	return m.ormConn.Model(&CmsPrefrenceAreaProductRelation{}).WithContext(ctx)
}

func (m *defaultCmsPrefrenceAreaProductRelationModel) Transaction(ctx context.Context, fc func(tx *gorm.DB) error, opts ...*sql.TxOptions) error {
	return m.ormConn.WithContext(ctx).Transaction(fc, opts...)
}

func (m *defaultCmsPrefrenceAreaProductRelationModel) FindPageListByBuilder(db *gorm.DB, page, pageSize int64) (*CmsPrefrenceAreaProductRelationPagination, error) {
	// 总行数
	var totalCount int64
	if err := db.Count(&totalCount).Error; err != nil {
		return nil, err
	}
	// 总页数
	totalPage := int64(math.Ceil(float64(totalCount) / float64(pageSize)))

	resp := new(CmsPrefrenceAreaProductRelationPagination)
	resp.PageSize = pageSize
	resp.TotalPage = totalPage
	resp.CurrentPage = page
	resp.TotalCount = totalCount

	// 没有数据则返回空数据
	if totalCount <= 0 {
		return resp, nil
	}
	// 当前页数没有数据也返回空数据
	if totalCount < ((page - 1) * pageSize) {
		return resp, nil
	}

	offset := int((page - 1) * pageSize)
	if err := db.Offset(offset).Limit(int(pageSize)).Find(&resp.Data).Error; err != nil {
		return nil, err
	}

	return resp, nil
}

func (m CmsPrefrenceAreaProductRelationPagination) Pagination() CmsPrefrenceAreaProductRelationPaginationBasic {
	return CmsPrefrenceAreaProductRelationPaginationBasic{
		CurrentPage: m.CurrentPage,
		PageSize:    m.PageSize,
		TotalPage:   m.TotalPage,
		TotalCount:  m.TotalCount,
	}
}

func (m CmsPrefrenceAreaProductRelationPagination) ToProto(to any, toData any, toPagination any) error {
	if to != nil {
		if err := copier.CopyWithOption(to, m, copier.Option{}); err != nil {
			return err
		}
	}
	if toData != nil {
		if err := copier.Copy(toData, m.Data); err != nil {
			return err
		}
	}
	if toPagination != nil {
		if err := copier.Copy(toPagination, m.Pagination()); err != nil {
			return err
		}
	}
	return nil
}

func (m *defaultCmsPrefrenceAreaProductRelationModel) Insert(ctx context.Context, data *CmsPrefrenceAreaProductRelation) error {
	return m.OrmSession(ctx).Create(data).Error
}

func (m *defaultCmsPrefrenceAreaProductRelationModel) Update(ctx context.Context, data *CmsPrefrenceAreaProductRelation) error {
	if data.Id <= 0 {
		return gorm.ErrMissingWhereClause
	}
	return m.OrmSession(ctx).Where("id = ?", data.Id).Save(data).Error
}
