// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"math"

	"fmt"
	"github.com/jinzhu/copier"
	"gorm.io/gorm"
)

var (
	_ sql.IsolationLevel
)

type (
	omsOrderSettingModel interface {
		Insert(ctx context.Context, data *OmsOrderSetting) error
		FindOne(ctx context.Context, id int64, preloadList ...string) (*OmsOrderSetting, error)
		OrmSession(ctx context.Context) *gorm.DB
		Transaction(ctx context.Context, fc func(tx *gorm.DB) error, opts ...*sql.TxOptions) error
		FindPageListByBuilder(ctx context.Context, keyword *KeywordOmsOrderSettingModel) (*OmsOrderSettingPagination, error)
		Update(ctx context.Context, data *OmsOrderSetting) error
		Delete(ctx context.Context, id int64) error
	}

	defaultOmsOrderSettingModel struct {
		table   string
		ormConn *gorm.DB
	}

	OmsOrderSetting struct {
		Id                  int64         `json:"id" gorm:"primary_key"`
		FlashOrderOvertime  sql.NullInt64 `json:"flash_order_overtime"`  // 秒杀订单超时关闭时间(分)
		NormalOrderOvertime sql.NullInt64 `json:"normal_order_overtime"` // 正常订单超时时间(分)
		ConfirmOvertime     sql.NullInt64 `json:"confirm_overtime"`      // 发货后自动确认收货时间（天）
		FinishOvertime      sql.NullInt64 `json:"finish_overtime"`       // 自动完成交易时间，不能申请售后（天）
		CommentOvertime     sql.NullInt64 `json:"comment_overtime"`      // 订单完成后自动好评时间（天）
		OmsOrderSettingRelation
	}

	OmsOrderSettingPagination struct {
		Data []*OmsOrderSetting
		OmsOrderSettingPaginationBasic
	}

	OmsOrderSettingPaginationBasic struct {
		CurrentPage int64
		PageSize    int64
		TotalCount  int64
		TotalPage   int64
	}

	KeywordOmsOrderSettingModel struct {
		KeywordKey     string //like 关键字
		KeywordValue   string //like 值
		Page, PageSize int64
	}
)

func newOmsOrderSettingModel(db *gorm.DB) *defaultOmsOrderSettingModel {
	return &defaultOmsOrderSettingModel{
		table:   "`oms_order_setting`",
		ormConn: db,
	}
}

func (OmsOrderSetting) TableName() string {
	return "`oms_order_setting`"
}

func (m OmsOrderSetting) ToProto(toValue interface{}) error {
	return copier.Copy(toValue, &m)
}

func (m *defaultOmsOrderSettingModel) Delete(ctx context.Context, id int64) error {
	return m.OrmSession(ctx).Delete(&OmsOrderSetting{}, id).Error
}

func (m *defaultOmsOrderSettingModel) FindOne(ctx context.Context, id int64, preloadList ...string) (*OmsOrderSetting, error) {
	var mm OmsOrderSetting
	db := m.OrmSession(ctx)
	for _, preload := range preloadList {
		db = db.Preload(preload)
	}
	err := db.First(&mm, id).Error
	switch err {
	case nil:
		return &mm, nil
	case gorm.ErrRecordNotFound:
		return nil, gorm.ErrRecordNotFound
	default:
		return nil, err
	}
}

func (m *defaultOmsOrderSettingModel) OrmSession(ctx context.Context) *gorm.DB {
	return m.ormConn.Model(&OmsOrderSetting{}).WithContext(ctx)
}

func (m *defaultOmsOrderSettingModel) Transaction(ctx context.Context, fc func(tx *gorm.DB) error, opts ...*sql.TxOptions) error {
	return m.ormConn.WithContext(ctx).Transaction(fc, opts...)
}

func (m *defaultOmsOrderSettingModel) FindPageListByBuilder(ctx context.Context, keyword *KeywordOmsOrderSettingModel) (*OmsOrderSettingPagination, error) {
	page := keyword.Page
	pageSize := keyword.PageSize
	// 总行数
	var totalCount int64
	db := m.OrmSession(ctx)
	if err := db.Count(&totalCount).Error; err != nil {
		return nil, err
	}
	// 总页数
	totalPage := int64(math.Ceil(float64(totalCount) / float64(pageSize)))

	resp := new(OmsOrderSettingPagination)
	resp.PageSize = pageSize
	resp.TotalPage = totalPage
	resp.CurrentPage = page
	resp.TotalCount = totalCount

	// 没有数据则返回空数据
	if totalCount <= 0 {
		return resp, nil
	}
	// 当前页数没有数据也返回空数据
	if totalCount < ((page - 1) * pageSize) {
		return resp, nil
	}
	if keyword.KeywordKey != "" && keyword.KeywordValue != "" {
		db = db.Where(fmt.Sprintf("%s = ?", keyword.KeywordKey), keyword.KeywordValue)
	}
	offset := int((page - 1) * pageSize)
	if err := db.Offset(offset).Limit(int(pageSize)).Find(&resp.Data).Error; err != nil {
		return nil, err
	}

	return resp, nil
}

func (m OmsOrderSettingPagination) Pagination() OmsOrderSettingPaginationBasic {
	return OmsOrderSettingPaginationBasic{
		CurrentPage: m.CurrentPage,
		PageSize:    m.PageSize,
		TotalPage:   m.TotalPage,
		TotalCount:  m.TotalCount,
	}
}

func (m OmsOrderSettingPagination) ToProto(to any, toData any, toPagination any) error {
	if to != nil {
		if err := copier.CopyWithOption(to, m, copier.Option{}); err != nil {
			return err
		}
	}
	if toData != nil {
		if err := copier.Copy(toData, m.Data); err != nil {
			return err
		}
	}
	if toPagination != nil {
		if err := copier.Copy(toPagination, m.Pagination()); err != nil {
			return err
		}
	}
	return nil
}

func (m *defaultOmsOrderSettingModel) Insert(ctx context.Context, data *OmsOrderSetting) error {
	return m.OrmSession(ctx).Create(data).Error
}

func (m *defaultOmsOrderSettingModel) Update(ctx context.Context, data *OmsOrderSetting) error {
	if data.Id <= 0 {
		return gorm.ErrMissingWhereClause
	}
	return m.OrmSession(ctx).Where("id = ?", data.Id).Save(data).Error
}
