// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"math"

	"github.com/jinzhu/copier"
	"gorm.io/gorm"
)

var (
	_ sql.IsolationLevel
)

type (
	omsOrderOperateHistoryModel interface {
		Insert(ctx context.Context, data *OmsOrderOperateHistory) error
		FindOne(ctx context.Context, id int64, preloadList ...string) (*OmsOrderOperateHistory, error)
		OrmSession(ctx context.Context) *gorm.DB
		Transaction(ctx context.Context, fc func(tx *gorm.DB) error, opts ...*sql.TxOptions) error
		FindPageListByBuilder(ormSession *gorm.DB, page, pageSize int64) (*OmsOrderOperateHistoryPagination, error)
		Update(ctx context.Context, data *OmsOrderOperateHistory) error
		Delete(ctx context.Context, id int64) error
	}

	defaultOmsOrderOperateHistoryModel struct {
		table   string
		ormConn *gorm.DB
	}

	OmsOrderOperateHistory struct {
		Id          int64          `json:"id" gorm:"primary_key"`
		OrderId     sql.NullInt64  `json:"order_id"`     // 订单id
		OperateMan  sql.NullString `json:"operate_man"`  // 操作人：用户；系统；后台管理员
		CreateTime  sql.NullTime   `json:"create_time"`  // 操作时间
		OrderStatus sql.NullInt64  `json:"order_status"` // 订单状态：0->待付款；1->待发货；2->已发货；3->已完成；4->已关闭；5->无效订单
		Note        sql.NullString `json:"note"`         // 备注
		OmsOrderOperateHistoryRelation
	}

	OmsOrderOperateHistoryPagination struct {
		Data []*OmsOrderOperateHistory
		OmsOrderOperateHistoryPaginationBasic
	}

	OmsOrderOperateHistoryPaginationBasic struct {
		CurrentPage int64
		PageSize    int64
		TotalCount  int64
		TotalPage   int64
	}
)

func newOmsOrderOperateHistoryModel(db *gorm.DB) *defaultOmsOrderOperateHistoryModel {
	return &defaultOmsOrderOperateHistoryModel{
		table:   "`oms_order_operate_history`",
		ormConn: db,
	}
}

func (OmsOrderOperateHistory) TableName() string {
	return "`oms_order_operate_history`"
}

func (m OmsOrderOperateHistory) ToProto(toValue interface{}) error {
	return copier.Copy(toValue, &m)
}

func (m *defaultOmsOrderOperateHistoryModel) Delete(ctx context.Context, id int64) error {
	return m.OrmSession(ctx).Delete(&OmsOrderOperateHistory{}, id).Error
}

func (m *defaultOmsOrderOperateHistoryModel) FindOne(ctx context.Context, id int64, preloadList ...string) (*OmsOrderOperateHistory, error) {
	var mm OmsOrderOperateHistory
	db := m.OrmSession(ctx)
	for _, preload := range preloadList {
		db = db.Preload(preload)
	}
	err := db.First(&mm, id).Error
	switch err {
	case nil:
		return &mm, nil
	case gorm.ErrRecordNotFound:
		return nil, gorm.ErrRecordNotFound
	default:
		return nil, err
	}
}

func (m *defaultOmsOrderOperateHistoryModel) OrmSession(ctx context.Context) *gorm.DB {
	return m.ormConn.Model(&OmsOrderOperateHistory{}).WithContext(ctx)
}

func (m *defaultOmsOrderOperateHistoryModel) Transaction(ctx context.Context, fc func(tx *gorm.DB) error, opts ...*sql.TxOptions) error {
	return m.ormConn.WithContext(ctx).Transaction(fc, opts...)
}

func (m *defaultOmsOrderOperateHistoryModel) FindPageListByBuilder(db *gorm.DB, page, pageSize int64) (*OmsOrderOperateHistoryPagination, error) {
	// 总行数
	var totalCount int64
	if err := db.Count(&totalCount).Error; err != nil {
		return nil, err
	}
	// 总页数
	totalPage := int64(math.Ceil(float64(totalCount) / float64(pageSize)))

	resp := new(OmsOrderOperateHistoryPagination)
	resp.PageSize = pageSize
	resp.TotalPage = totalPage
	resp.CurrentPage = page
	resp.TotalCount = totalCount

	// 没有数据则返回空数据
	if totalCount <= 0 {
		return resp, nil
	}
	// 当前页数没有数据也返回空数据
	if totalCount < ((page - 1) * pageSize) {
		return resp, nil
	}

	offset := int((page - 1) * pageSize)
	if err := db.Offset(offset).Limit(int(pageSize)).Find(&resp.Data).Error; err != nil {
		return nil, err
	}

	return resp, nil
}

func (m OmsOrderOperateHistoryPagination) Pagination() OmsOrderOperateHistoryPaginationBasic {
	return OmsOrderOperateHistoryPaginationBasic{
		CurrentPage: m.CurrentPage,
		PageSize:    m.PageSize,
		TotalPage:   m.TotalPage,
		TotalCount:  m.TotalCount,
	}
}

func (m OmsOrderOperateHistoryPagination) ToProto(to any, toData any, toPagination any) error {
	if to != nil {
		if err := copier.CopyWithOption(to, m, copier.Option{}); err != nil {
			return err
		}
	}
	if toData != nil {
		if err := copier.Copy(toData, m.Data); err != nil {
			return err
		}
	}
	if toPagination != nil {
		if err := copier.Copy(toPagination, m.Pagination()); err != nil {
			return err
		}
	}
	return nil
}

func (m *defaultOmsOrderOperateHistoryModel) Insert(ctx context.Context, data *OmsOrderOperateHistory) error {
	return m.OrmSession(ctx).Create(data).Error
}

func (m *defaultOmsOrderOperateHistoryModel) Update(ctx context.Context, data *OmsOrderOperateHistory) error {
	if data.Id <= 0 {
		return gorm.ErrMissingWhereClause
	}
	return m.OrmSession(ctx).Where("id = ?", data.Id).Save(data).Error
}
