// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"math"

	"fmt"
	"github.com/jinzhu/copier"
	"gorm.io/gorm"
)

var (
	_ sql.IsolationLevel
)

type (
	omsOrderReturnReasonModel interface {
		Insert(ctx context.Context, data *OmsOrderReturnReason) error
		FindOne(ctx context.Context, id int64, preloadList ...string) (*OmsOrderReturnReason, error)
		OrmSession(ctx context.Context) *gorm.DB
		Transaction(ctx context.Context, fc func(tx *gorm.DB) error, opts ...*sql.TxOptions) error
		FindPageListByBuilder(ormSession *gorm.DB, keyword *KeywordOmsOrderReturnReasonModel) (*OmsOrderReturnReasonPagination, error)
		Update(ctx context.Context, data *OmsOrderReturnReason) error
		Delete(ctx context.Context, id int64) error
	}

	defaultOmsOrderReturnReasonModel struct {
		table   string
		ormConn *gorm.DB
	}

	OmsOrderReturnReason struct {
		Id         int64          `json:"id" gorm:"primary_key"`
		Name       sql.NullString `json:"name"` // 退货类型
		Sort       sql.NullInt64  `json:"sort"`
		Status     sql.NullInt64  `json:"status"`      // 状态：0->不启用；1->启用
		CreateTime sql.NullTime   `json:"create_time"` // 添加时间
		OmsOrderReturnReasonRelation
	}

	OmsOrderReturnReasonPagination struct {
		Data []*OmsOrderReturnReason
		OmsOrderReturnReasonPaginationBasic
	}

	OmsOrderReturnReasonPaginationBasic struct {
		CurrentPage int64
		PageSize    int64
		TotalCount  int64
		TotalPage   int64
	}

	KeywordOmsOrderReturnReasonModel struct {
		KeywordKey     string //like 关键字
		KeywordValue   string //like 值
		Page, PageSize int64
	}
)

func newOmsOrderReturnReasonModel(db *gorm.DB) *defaultOmsOrderReturnReasonModel {
	return &defaultOmsOrderReturnReasonModel{
		table:   "`oms_order_return_reason`",
		ormConn: db,
	}
}

func (OmsOrderReturnReason) TableName() string {
	return "`oms_order_return_reason`"
}

func (m OmsOrderReturnReason) ToProto(toValue interface{}) error {
	return copier.Copy(toValue, &m)
}

func (m *defaultOmsOrderReturnReasonModel) Delete(ctx context.Context, id int64) error {
	return m.OrmSession(ctx).Delete(&OmsOrderReturnReason{}, id).Error
}

func (m *defaultOmsOrderReturnReasonModel) FindOne(ctx context.Context, id int64, preloadList ...string) (*OmsOrderReturnReason, error) {
	var mm OmsOrderReturnReason
	db := m.OrmSession(ctx)
	for _, preload := range preloadList {
		db = db.Preload(preload)
	}
	err := db.First(&mm, id).Error
	switch err {
	case nil:
		return &mm, nil
	case gorm.ErrRecordNotFound:
		return nil, gorm.ErrRecordNotFound
	default:
		return nil, err
	}
}

func (m *defaultOmsOrderReturnReasonModel) OrmSession(ctx context.Context) *gorm.DB {
	return m.ormConn.Model(&OmsOrderReturnReason{}).WithContext(ctx)
}

func (m *defaultOmsOrderReturnReasonModel) Transaction(ctx context.Context, fc func(tx *gorm.DB) error, opts ...*sql.TxOptions) error {
	return m.ormConn.WithContext(ctx).Transaction(fc, opts...)
}

func (m *defaultOmsOrderReturnReasonModel) FindPageListByBuilder(db *gorm.DB, keyword *KeywordOmsOrderReturnReasonModel) (*OmsOrderReturnReasonPagination, error) {
	page := keyword.Page
	pageSize := keyword.PageSize
	// 总行数
	var totalCount int64
	if err := db.Count(&totalCount).Error; err != nil {
		return nil, err
	}
	// 总页数
	totalPage := int64(math.Ceil(float64(totalCount) / float64(pageSize)))

	resp := new(OmsOrderReturnReasonPagination)
	resp.PageSize = pageSize
	resp.TotalPage = totalPage
	resp.CurrentPage = page
	resp.TotalCount = totalCount

	// 没有数据则返回空数据
	if totalCount <= 0 {
		return resp, nil
	}
	// 当前页数没有数据也返回空数据
	if totalCount < ((page - 1) * pageSize) {
		return resp, nil
	}
	if keyword.KeywordKey != "" && keyword.KeywordValue != "" {
		db = db.Where(fmt.Sprintf("%s = ?", keyword.KeywordKey), keyword.KeywordValue)
	}
	offset := int((page - 1) * pageSize)
	if err := db.Offset(offset).Limit(int(pageSize)).Find(&resp.Data).Error; err != nil {
		return nil, err
	}

	return resp, nil
}

func (m OmsOrderReturnReasonPagination) Pagination() OmsOrderReturnReasonPaginationBasic {
	return OmsOrderReturnReasonPaginationBasic{
		CurrentPage: m.CurrentPage,
		PageSize:    m.PageSize,
		TotalPage:   m.TotalPage,
		TotalCount:  m.TotalCount,
	}
}

func (m OmsOrderReturnReasonPagination) ToProto(to any, toData any, toPagination any) error {
	if to != nil {
		if err := copier.CopyWithOption(to, m, copier.Option{}); err != nil {
			return err
		}
	}
	if toData != nil {
		if err := copier.Copy(toData, m.Data); err != nil {
			return err
		}
	}
	if toPagination != nil {
		if err := copier.Copy(toPagination, m.Pagination()); err != nil {
			return err
		}
	}
	return nil
}

func (m *defaultOmsOrderReturnReasonModel) Insert(ctx context.Context, data *OmsOrderReturnReason) error {
	return m.OrmSession(ctx).Create(data).Error
}

func (m *defaultOmsOrderReturnReasonModel) Update(ctx context.Context, data *OmsOrderReturnReason) error {
	if data.Id <= 0 {
		return gorm.ErrMissingWhereClause
	}
	return m.OrmSession(ctx).Where("id = ?", data.Id).Save(data).Error
}
