// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"math"

	"github.com/jinzhu/copier"
	"gorm.io/gorm"
)

var (
	_ sql.IsolationLevel
)

type (
	pmsProductOperateLogModel interface {
		Insert(ctx context.Context, data *PmsProductOperateLog) error
		FindOne(ctx context.Context, id int64, preloadList ...string) (*PmsProductOperateLog, error)
		OrmSession(ctx context.Context) *gorm.DB
		Transaction(ctx context.Context, fc func(tx *gorm.DB) error, opts ...*sql.TxOptions) error
		FindPageListByBuilder(ormSession *gorm.DB, keyword *KeywordPmsProductOperateLogModel) (*PmsProductOperateLogPagination, error)
		Update(ctx context.Context, data *PmsProductOperateLog) error
		Delete(ctx context.Context, id int64) error
	}

	defaultPmsProductOperateLogModel struct {
		table   string
		ormConn *gorm.DB
	}

	PmsProductOperateLog struct {
		Id               int64           `json:"id" gorm:"primary_key"`
		ProductId        sql.NullInt64   `json:"product_id"`
		PriceOld         sql.NullFloat64 `json:"price_old"`
		PriceNew         sql.NullFloat64 `json:"price_new"`
		SalePriceOld     sql.NullFloat64 `json:"sale_price_old"`
		SalePriceNew     sql.NullFloat64 `json:"sale_price_new"`
		GiftPointOld     sql.NullInt64   `json:"gift_point_old"` // 赠送的积分
		GiftPointNew     sql.NullInt64   `json:"gift_point_new"`
		UsePointLimitOld sql.NullInt64   `json:"use_point_limit_old"`
		UsePointLimitNew sql.NullInt64   `json:"use_point_limit_new"`
		OperateMan       sql.NullString  `json:"operate_man"` // 操作人
		CreateTime       sql.NullTime    `json:"create_time"`
		PmsProductOperateLogRelation
	}

	PmsProductOperateLogPagination struct {
		Data []*PmsProductOperateLog
		PmsProductOperateLogPaginationBasic
	}

	PmsProductOperateLogPaginationBasic struct {
		CurrentPage int64
		PageSize    int64
		TotalCount  int64
		TotalPage   int64
	}

	KeywordPmsProductOperateLogModel struct {
		KeywordKey     string //like 关键字
		KeywordValue   string //like 值
		Page, PageSize int64
	}
)

func newPmsProductOperateLogModel(db *gorm.DB) *defaultPmsProductOperateLogModel {
	return &defaultPmsProductOperateLogModel{
		table:   "`pms_product_operate_log`",
		ormConn: db,
	}
}

func (PmsProductOperateLog) TableName() string {
	return "`pms_product_operate_log`"
}

func (m PmsProductOperateLog) ToProto(toValue interface{}) error {
	return copier.Copy(toValue, &m)
}

func (m *defaultPmsProductOperateLogModel) Delete(ctx context.Context, id int64) error {
	return m.OrmSession(ctx).Delete(&PmsProductOperateLog{}, id).Error
}

func (m *defaultPmsProductOperateLogModel) FindOne(ctx context.Context, id int64, preloadList ...string) (*PmsProductOperateLog, error) {
	var mm PmsProductOperateLog
	db := m.OrmSession(ctx)
	for _, preload := range preloadList {
		db = db.Preload(preload)
	}
	err := db.First(&mm, id).Error
	switch err {
	case nil:
		return &mm, nil
	case gorm.ErrRecordNotFound:
		return nil, gorm.ErrRecordNotFound
	default:
		return nil, err
	}
}

func (m *defaultPmsProductOperateLogModel) OrmSession(ctx context.Context) *gorm.DB {
	return m.ormConn.Model(&PmsProductOperateLog{}).WithContext(ctx)
}

func (m *defaultPmsProductOperateLogModel) Transaction(ctx context.Context, fc func(tx *gorm.DB) error, opts ...*sql.TxOptions) error {
	return m.ormConn.WithContext(ctx).Transaction(fc, opts...)
}

func (m *defaultPmsProductOperateLogModel) FindPageListByBuilder(db *gorm.DB, keyword *KeywordPmsProductOperateLogModel) (*PmsProductOperateLogPagination, error) {
	page := keyword.Page
	pageSize := keyword.PageSize
	// 总行数
	var totalCount int64
	if err := db.Count(&totalCount).Error; err != nil {
		return nil, err
	}
	// 总页数
	totalPage := int64(math.Ceil(float64(totalCount) / float64(pageSize)))

	resp := new(PmsProductOperateLogPagination)
	resp.PageSize = pageSize
	resp.TotalPage = totalPage
	resp.CurrentPage = page
	resp.TotalCount = totalCount

	// 没有数据则返回空数据
	if totalCount <= 0 {
		return resp, nil
	}
	// 当前页数没有数据也返回空数据
	if totalCount < ((page - 1) * pageSize) {
		return resp, nil
	}
	if keyword.KeywordKey != "" && keyword.KeywordValue != "" {
		db = db.Where(fmt.Sprintf("%s = ?", keyword.KeywordKey), keyword.KeywordValue)
	}
	offset := int((page - 1) * pageSize)
	if err := db.Offset(offset).Limit(int(pageSize)).Find(&resp.Data).Error; err != nil {
		return nil, err
	}

	return resp, nil
}

func (m PmsProductOperateLogPagination) Pagination() PmsProductOperateLogPaginationBasic {
	return PmsProductOperateLogPaginationBasic{
		CurrentPage: m.CurrentPage,
		PageSize:    m.PageSize,
		TotalPage:   m.TotalPage,
		TotalCount:  m.TotalCount,
	}
}

func (m PmsProductOperateLogPagination) ToProto(to any, toData any, toPagination any) error {
	if to != nil {
		if err := copier.CopyWithOption(to, m, copier.Option{}); err != nil {
			return err
		}
	}
	if toData != nil {
		if err := copier.Copy(toData, m.Data); err != nil {
			return err
		}
	}
	if toPagination != nil {
		if err := copier.Copy(toPagination, m.Pagination()); err != nil {
			return err
		}
	}
	return nil
}

func (m *defaultPmsProductOperateLogModel) Insert(ctx context.Context, data *PmsProductOperateLog) error {
	return m.OrmSession(ctx).Create(data).Error
}

func (m *defaultPmsProductOperateLogModel) Update(ctx context.Context, data *PmsProductOperateLog) error {
	if data.Id <= 0 {
		return gorm.ErrMissingWhereClause
	}
	return m.OrmSession(ctx).Where("id = ?", data.Id).Save(data).Error
}
