// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"math"

	"fmt"
	"github.com/jinzhu/copier"
	"gorm.io/gorm"
)

var (
	_ sql.IsolationLevel
)

type (
	pmsProductVertifyRecordModel interface {
		Insert(ctx context.Context, data *PmsProductVertifyRecord) error
		FindOne(ctx context.Context, id int64, preloadList ...string) (*PmsProductVertifyRecord, error)
		OrmSession(ctx context.Context) *gorm.DB
		Transaction(ctx context.Context, fc func(tx *gorm.DB) error, opts ...*sql.TxOptions) error
		FindPageListByBuilder(ctx context.Context, keyword *KeywordPmsProductVertifyRecordModel) (*PmsProductVertifyRecordPagination, error)
		Update(ctx context.Context, data *PmsProductVertifyRecord) error
		Delete(ctx context.Context, id int64) error
	}

	defaultPmsProductVertifyRecordModel struct {
		table   string
		ormConn *gorm.DB
	}

	PmsProductVertifyRecord struct {
		Id         int64          `json:"id" gorm:"primary_key"`
		ProductId  sql.NullInt64  `json:"product_id"`
		CreateTime sql.NullTime   `json:"create_time"`
		VertifyMan sql.NullString `json:"vertify_man"` // 审核人
		Status     sql.NullInt64  `json:"status"`
		Detail     sql.NullString `json:"detail"` // 反馈详情
		PmsProductVertifyRecordRelation
	}

	PmsProductVertifyRecordPagination struct {
		Data []*PmsProductVertifyRecord
		PmsProductVertifyRecordPaginationBasic
	}

	PmsProductVertifyRecordPaginationBasic struct {
		CurrentPage int64
		PageSize    int64
		TotalCount  int64
		TotalPage   int64
	}

	KeywordPmsProductVertifyRecordModel struct {
		KeywordKey     string //like 关键字
		KeywordValue   string //like 值
		Page, PageSize int64
	}
)

func newPmsProductVertifyRecordModel(db *gorm.DB) *defaultPmsProductVertifyRecordModel {
	return &defaultPmsProductVertifyRecordModel{
		table:   "`pms_product_vertify_record`",
		ormConn: db,
	}
}

func (PmsProductVertifyRecord) TableName() string {
	return "`pms_product_vertify_record`"
}

func (m PmsProductVertifyRecord) ToProto(toValue interface{}) error {
	return copier.Copy(toValue, &m)
}

func (m *defaultPmsProductVertifyRecordModel) Delete(ctx context.Context, id int64) error {
	return m.OrmSession(ctx).Delete(&PmsProductVertifyRecord{}, id).Error
}

func (m *defaultPmsProductVertifyRecordModel) FindOne(ctx context.Context, id int64, preloadList ...string) (*PmsProductVertifyRecord, error) {
	var mm PmsProductVertifyRecord
	db := m.OrmSession(ctx)
	for _, preload := range preloadList {
		db = db.Preload(preload)
	}
	err := db.First(&mm, id).Error
	switch err {
	case nil:
		return &mm, nil
	case gorm.ErrRecordNotFound:
		return nil, gorm.ErrRecordNotFound
	default:
		return nil, err
	}
}

func (m *defaultPmsProductVertifyRecordModel) OrmSession(ctx context.Context) *gorm.DB {
	return m.ormConn.Model(&PmsProductVertifyRecord{}).WithContext(ctx)
}

func (m *defaultPmsProductVertifyRecordModel) Transaction(ctx context.Context, fc func(tx *gorm.DB) error, opts ...*sql.TxOptions) error {
	return m.ormConn.WithContext(ctx).Transaction(fc, opts...)
}

func (m *defaultPmsProductVertifyRecordModel) FindPageListByBuilder(ctx context.Context, keyword *KeywordPmsProductVertifyRecordModel) (*PmsProductVertifyRecordPagination, error) {
	page := keyword.Page
	pageSize := keyword.PageSize
	// 总行数
	var totalCount int64
	db := m.OrmSession(ctx)
	if err := db.Count(&totalCount).Error; err != nil {
		return nil, err
	}
	// 总页数
	totalPage := int64(math.Ceil(float64(totalCount) / float64(pageSize)))

	resp := new(PmsProductVertifyRecordPagination)
	resp.PageSize = pageSize
	resp.TotalPage = totalPage
	resp.CurrentPage = page
	resp.TotalCount = totalCount

	// 没有数据则返回空数据
	if totalCount <= 0 {
		return resp, nil
	}
	// 当前页数没有数据也返回空数据
	if totalCount < ((page - 1) * pageSize) {
		return resp, nil
	}
	if keyword.KeywordKey != "" && keyword.KeywordValue != "" {
		db = db.Where(fmt.Sprintf("%s = ?", keyword.KeywordKey), keyword.KeywordValue)
	}
	offset := int((page - 1) * pageSize)
	if err := db.Offset(offset).Limit(int(pageSize)).Find(&resp.Data).Error; err != nil {
		return nil, err
	}

	return resp, nil
}

func (m PmsProductVertifyRecordPagination) Pagination() PmsProductVertifyRecordPaginationBasic {
	return PmsProductVertifyRecordPaginationBasic{
		CurrentPage: m.CurrentPage,
		PageSize:    m.PageSize,
		TotalPage:   m.TotalPage,
		TotalCount:  m.TotalCount,
	}
}

func (m PmsProductVertifyRecordPagination) ToProto(to any, toData any, toPagination any) error {
	if to != nil {
		if err := copier.CopyWithOption(to, m, copier.Option{}); err != nil {
			return err
		}
	}
	if toData != nil {
		if err := copier.Copy(toData, m.Data); err != nil {
			return err
		}
	}
	if toPagination != nil {
		if err := copier.Copy(toPagination, m.Pagination()); err != nil {
			return err
		}
	}
	return nil
}

func (m *defaultPmsProductVertifyRecordModel) Insert(ctx context.Context, data *PmsProductVertifyRecord) error {
	return m.OrmSession(ctx).Create(data).Error
}

func (m *defaultPmsProductVertifyRecordModel) Update(ctx context.Context, data *PmsProductVertifyRecord) error {
	if data.Id <= 0 {
		return gorm.ErrMissingWhereClause
	}
	return m.OrmSession(ctx).Where("id = ?", data.Id).Save(data).Error
}
