// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"math"

	"github.com/jinzhu/copier"
	"gorm.io/gorm"
)

var (
	_ sql.IsolationLevel
)

type (
	pmsProductLadderModel interface {
		Insert(ctx context.Context, data *PmsProductLadder) error
		FindOne(ctx context.Context, id int64, preloadList ...string) (*PmsProductLadder, error)
		OrmSession(ctx context.Context) *gorm.DB
		Transaction(ctx context.Context, fc func(tx *gorm.DB) error, opts ...*sql.TxOptions) error
		FindPageListByBuilder(ormSession *gorm.DB, page, pageSize int64) (*PmsProductLadderPagination, error)
		Update(ctx context.Context, data *PmsProductLadder) error
		Delete(ctx context.Context, id int64) error
	}

	defaultPmsProductLadderModel struct {
		table   string
		ormConn *gorm.DB
	}

	PmsProductLadder struct {
		Id        int64           `json:"id" gorm:"primary_key"`
		ProductId sql.NullInt64   `json:"product_id"`
		Count     sql.NullInt64   `json:"count"`    // 满足的商品数量
		Discount  sql.NullFloat64 `json:"discount"` // 折扣
		Price     sql.NullFloat64 `json:"price"`    // 折后价格
		PmsProductLadderRelation
	}

	PmsProductLadderPagination struct {
		Data []*PmsProductLadder
		PmsProductLadderPaginationBasic
	}

	PmsProductLadderPaginationBasic struct {
		CurrentPage int64
		PageSize    int64
		TotalCount  int64
		TotalPage   int64
	}
)

func newPmsProductLadderModel(db *gorm.DB) *defaultPmsProductLadderModel {
	return &defaultPmsProductLadderModel{
		table:   "`pms_product_ladder`",
		ormConn: db,
	}
}

func (PmsProductLadder) TableName() string {
	return "`pms_product_ladder`"
}

func (m PmsProductLadder) ToProto(toValue interface{}) error {
	return copier.Copy(toValue, &m)
}

func (m *defaultPmsProductLadderModel) Delete(ctx context.Context, id int64) error {
	return m.OrmSession(ctx).Delete(&PmsProductLadder{}, id).Error
}

func (m *defaultPmsProductLadderModel) FindOne(ctx context.Context, id int64, preloadList ...string) (*PmsProductLadder, error) {
	var mm PmsProductLadder
	db := m.OrmSession(ctx)
	for _, preload := range preloadList {
		db = db.Preload(preload)
	}
	err := db.First(&mm, id).Error
	switch err {
	case nil:
		return &mm, nil
	case gorm.ErrRecordNotFound:
		return nil, gorm.ErrRecordNotFound
	default:
		return nil, err
	}
}

func (m *defaultPmsProductLadderModel) OrmSession(ctx context.Context) *gorm.DB {
	return m.ormConn.Model(&PmsProductLadder{}).WithContext(ctx)
}

func (m *defaultPmsProductLadderModel) Transaction(ctx context.Context, fc func(tx *gorm.DB) error, opts ...*sql.TxOptions) error {
	return m.ormConn.WithContext(ctx).Transaction(fc, opts...)
}

func (m *defaultPmsProductLadderModel) FindPageListByBuilder(db *gorm.DB, page, pageSize int64) (*PmsProductLadderPagination, error) {
	// 总行数
	var totalCount int64
	if err := db.Count(&totalCount).Error; err != nil {
		return nil, err
	}
	// 总页数
	totalPage := int64(math.Ceil(float64(totalCount) / float64(pageSize)))

	resp := new(PmsProductLadderPagination)
	resp.PageSize = pageSize
	resp.TotalPage = totalPage
	resp.CurrentPage = page
	resp.TotalCount = totalCount

	// 没有数据则返回空数据
	if totalCount <= 0 {
		return resp, nil
	}
	// 当前页数没有数据也返回空数据
	if totalCount < ((page - 1) * pageSize) {
		return resp, nil
	}

	offset := int((page - 1) * pageSize)
	if err := db.Offset(offset).Limit(int(pageSize)).Find(&resp.Data).Error; err != nil {
		return nil, err
	}

	return resp, nil
}

func (m PmsProductLadderPagination) Pagination() PmsProductLadderPaginationBasic {
	return PmsProductLadderPaginationBasic{
		CurrentPage: m.CurrentPage,
		PageSize:    m.PageSize,
		TotalPage:   m.TotalPage,
		TotalCount:  m.TotalCount,
	}
}

func (m PmsProductLadderPagination) ToProto(to any, toData any, toPagination any) error {
	if to != nil {
		if err := copier.CopyWithOption(to, m, copier.Option{}); err != nil {
			return err
		}
	}
	if toData != nil {
		if err := copier.Copy(toData, m.Data); err != nil {
			return err
		}
	}
	if toPagination != nil {
		if err := copier.Copy(toPagination, m.Pagination()); err != nil {
			return err
		}
	}
	return nil
}

func (m *defaultPmsProductLadderModel) Insert(ctx context.Context, data *PmsProductLadder) error {
	return m.OrmSession(ctx).Create(data).Error
}

func (m *defaultPmsProductLadderModel) Update(ctx context.Context, data *PmsProductLadder) error {
	if data.Id <= 0 {
		return gorm.ErrMissingWhereClause
	}
	return m.OrmSession(ctx).Where("id = ?", data.Id).Save(data).Error
}
