// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"math"

	"fmt"
	"github.com/jinzhu/copier"
	"gorm.io/gorm"
)

var (
	_ sql.IsolationLevel
)

type (
	pmsProductAttributeModel interface {
		Insert(ctx context.Context, data *PmsProductAttribute) error
		FindOne(ctx context.Context, id int64, preloadList ...string) (*PmsProductAttribute, error)
		OrmSession(ctx context.Context) *gorm.DB
		Transaction(ctx context.Context, fc func(tx *gorm.DB) error, opts ...*sql.TxOptions) error
		FindPageListByBuilder(ormSession *gorm.DB, keyword *KeywordPmsProductAttributeModel) (*PmsProductAttributePagination, error)
		Update(ctx context.Context, data *PmsProductAttribute) error
		Delete(ctx context.Context, id int64) error
	}

	defaultPmsProductAttributeModel struct {
		table   string
		ormConn *gorm.DB
	}

	PmsProductAttribute struct {
		Id                         int64          `json:"id" gorm:"primary_key"`
		ProductAttributeCategoryId sql.NullInt64  `json:"product_attribute_category_id"`
		Name                       sql.NullString `json:"name"`
		SelectType                 sql.NullInt64  `json:"select_type"`     // 属性选择类型：0->唯一；1->单选；2->多选
		InputType                  sql.NullInt64  `json:"input_type"`      // 属性录入方式：0->手工录入；1->从列表中选取
		InputList                  sql.NullString `json:"input_list"`      // 可选值列表，以逗号隔开
		Sort                       sql.NullInt64  `json:"sort"`            // 排序字段：最高的可以单独上传图片
		FilterType                 sql.NullInt64  `json:"filter_type"`     // 分类筛选样式：1->普通；1->颜色
		SearchType                 sql.NullInt64  `json:"search_type"`     // 检索类型；0->不需要进行检索；1->关键字检索；2->范围检索
		RelatedStatus              sql.NullInt64  `json:"related_status"`  // 相同属性产品是否关联；0->不关联；1->关联
		HandAddStatus              sql.NullInt64  `json:"hand_add_status"` // 是否支持手动新增；0->不支持；1->支持
		Type                       sql.NullInt64  `json:"type"`            // 属性的类型；0->规格；1->参数
		PmsProductAttributeRelation
	}

	PmsProductAttributePagination struct {
		Data []*PmsProductAttribute
		PmsProductAttributePaginationBasic
	}

	PmsProductAttributePaginationBasic struct {
		CurrentPage int64
		PageSize    int64
		TotalCount  int64
		TotalPage   int64
	}

	KeywordPmsProductAttributeModel struct {
		KeywordKey     string //like 关键字
		KeywordValue   string //like 值
		Page, PageSize int64
	}
)

func newPmsProductAttributeModel(db *gorm.DB) *defaultPmsProductAttributeModel {
	return &defaultPmsProductAttributeModel{
		table:   "`pms_product_attribute`",
		ormConn: db,
	}
}

func (PmsProductAttribute) TableName() string {
	return "`pms_product_attribute`"
}

func (m PmsProductAttribute) ToProto(toValue interface{}) error {
	return copier.Copy(toValue, &m)
}

func (m *defaultPmsProductAttributeModel) Delete(ctx context.Context, id int64) error {
	return m.OrmSession(ctx).Delete(&PmsProductAttribute{}, id).Error
}

func (m *defaultPmsProductAttributeModel) FindOne(ctx context.Context, id int64, preloadList ...string) (*PmsProductAttribute, error) {
	var mm PmsProductAttribute
	db := m.OrmSession(ctx)
	for _, preload := range preloadList {
		db = db.Preload(preload)
	}
	err := db.First(&mm, id).Error
	switch err {
	case nil:
		return &mm, nil
	case gorm.ErrRecordNotFound:
		return nil, gorm.ErrRecordNotFound
	default:
		return nil, err
	}
}

func (m *defaultPmsProductAttributeModel) OrmSession(ctx context.Context) *gorm.DB {
	return m.ormConn.Model(&PmsProductAttribute{}).WithContext(ctx)
}

func (m *defaultPmsProductAttributeModel) Transaction(ctx context.Context, fc func(tx *gorm.DB) error, opts ...*sql.TxOptions) error {
	return m.ormConn.WithContext(ctx).Transaction(fc, opts...)
}

func (m *defaultPmsProductAttributeModel) FindPageListByBuilder(db *gorm.DB, keyword *KeywordPmsProductAttributeModel) (*PmsProductAttributePagination, error) {
	page := keyword.Page
	pageSize := keyword.PageSize
	// 总行数
	var totalCount int64
	if err := db.Count(&totalCount).Error; err != nil {
		return nil, err
	}
	// 总页数
	totalPage := int64(math.Ceil(float64(totalCount) / float64(pageSize)))

	resp := new(PmsProductAttributePagination)
	resp.PageSize = pageSize
	resp.TotalPage = totalPage
	resp.CurrentPage = page
	resp.TotalCount = totalCount

	// 没有数据则返回空数据
	if totalCount <= 0 {
		return resp, nil
	}
	// 当前页数没有数据也返回空数据
	if totalCount < ((page - 1) * pageSize) {
		return resp, nil
	}
	if keyword.KeywordKey != "" && keyword.KeywordValue != "" {
		db = db.Where(fmt.Sprintf("%s = ?", keyword.KeywordKey), keyword.KeywordValue)
	}
	offset := int((page - 1) * pageSize)
	if err := db.Offset(offset).Limit(int(pageSize)).Find(&resp.Data).Error; err != nil {
		return nil, err
	}

	return resp, nil
}

func (m PmsProductAttributePagination) Pagination() PmsProductAttributePaginationBasic {
	return PmsProductAttributePaginationBasic{
		CurrentPage: m.CurrentPage,
		PageSize:    m.PageSize,
		TotalPage:   m.TotalPage,
		TotalCount:  m.TotalCount,
	}
}

func (m PmsProductAttributePagination) ToProto(to any, toData any, toPagination any) error {
	if to != nil {
		if err := copier.CopyWithOption(to, m, copier.Option{}); err != nil {
			return err
		}
	}
	if toData != nil {
		if err := copier.Copy(toData, m.Data); err != nil {
			return err
		}
	}
	if toPagination != nil {
		if err := copier.Copy(toPagination, m.Pagination()); err != nil {
			return err
		}
	}
	return nil
}

func (m *defaultPmsProductAttributeModel) Insert(ctx context.Context, data *PmsProductAttribute) error {
	return m.OrmSession(ctx).Create(data).Error
}

func (m *defaultPmsProductAttributeModel) Update(ctx context.Context, data *PmsProductAttribute) error {
	if data.Id <= 0 {
		return gorm.ErrMissingWhereClause
	}
	return m.OrmSession(ctx).Where("id = ?", data.Id).Save(data).Error
}
