// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"math"

	"fmt"
	"github.com/jinzhu/copier"
	"gorm.io/gorm"
)

var (
	_ sql.IsolationLevel
)

type (
	pmsProductAttributeValueModel interface {
		Insert(ctx context.Context, data *PmsProductAttributeValue) error
		FindOne(ctx context.Context, id int64, preloadList ...string) (*PmsProductAttributeValue, error)
		OrmSession(ctx context.Context) *gorm.DB
		Transaction(ctx context.Context, fc func(tx *gorm.DB) error, opts ...*sql.TxOptions) error
		FindPageListByBuilder(ctx context.Context, keyword *KeywordPmsProductAttributeValueModel) (*PmsProductAttributeValuePagination, error)
		Update(ctx context.Context, data *PmsProductAttributeValue) error
		Delete(ctx context.Context, id int64) error
	}

	defaultPmsProductAttributeValueModel struct {
		table   string
		ormConn *gorm.DB
	}

	PmsProductAttributeValue struct {
		Id                 int64          `json:"id" gorm:"primary_key"`
		ProductId          sql.NullInt64  `json:"product_id"`
		ProductAttributeId sql.NullInt64  `json:"product_attribute_id"`
		Value              sql.NullString `json:"value"` // 手动添加规格或参数的值，参数单值，规格有多个时以逗号隔开
		PmsProductAttributeValueRelation
	}

	PmsProductAttributeValuePagination struct {
		Data []*PmsProductAttributeValue
		PmsProductAttributeValuePaginationBasic
	}

	PmsProductAttributeValuePaginationBasic struct {
		CurrentPage int64
		PageSize    int64
		TotalCount  int64
		TotalPage   int64
	}

	KeywordPmsProductAttributeValueModel struct {
		KeywordKey     string //like 关键字
		KeywordValue   string //like 值
		Page, PageSize int64
	}
)

func newPmsProductAttributeValueModel(db *gorm.DB) *defaultPmsProductAttributeValueModel {
	return &defaultPmsProductAttributeValueModel{
		table:   "`pms_product_attribute_value`",
		ormConn: db,
	}
}

func (PmsProductAttributeValue) TableName() string {
	return "`pms_product_attribute_value`"
}

func (m PmsProductAttributeValue) ToProto(toValue interface{}) error {
	return copier.Copy(toValue, &m)
}

func (m *defaultPmsProductAttributeValueModel) Delete(ctx context.Context, id int64) error {
	return m.OrmSession(ctx).Delete(&PmsProductAttributeValue{}, id).Error
}

func (m *defaultPmsProductAttributeValueModel) FindOne(ctx context.Context, id int64, preloadList ...string) (*PmsProductAttributeValue, error) {
	var mm PmsProductAttributeValue
	db := m.OrmSession(ctx)
	for _, preload := range preloadList {
		db = db.Preload(preload)
	}
	err := db.First(&mm, id).Error
	switch err {
	case nil:
		return &mm, nil
	case gorm.ErrRecordNotFound:
		return nil, gorm.ErrRecordNotFound
	default:
		return nil, err
	}
}

func (m *defaultPmsProductAttributeValueModel) OrmSession(ctx context.Context) *gorm.DB {
	return m.ormConn.Model(&PmsProductAttributeValue{}).WithContext(ctx)
}

func (m *defaultPmsProductAttributeValueModel) Transaction(ctx context.Context, fc func(tx *gorm.DB) error, opts ...*sql.TxOptions) error {
	return m.ormConn.WithContext(ctx).Transaction(fc, opts...)
}

func (m *defaultPmsProductAttributeValueModel) FindPageListByBuilder(ctx context.Context, keyword *KeywordPmsProductAttributeValueModel) (*PmsProductAttributeValuePagination, error) {
	page := keyword.Page
	pageSize := keyword.PageSize
	// 总行数
	var totalCount int64
	db := m.OrmSession(ctx)
	if err := db.Count(&totalCount).Error; err != nil {
		return nil, err
	}
	// 总页数
	totalPage := int64(math.Ceil(float64(totalCount) / float64(pageSize)))

	resp := new(PmsProductAttributeValuePagination)
	resp.PageSize = pageSize
	resp.TotalPage = totalPage
	resp.CurrentPage = page
	resp.TotalCount = totalCount

	// 没有数据则返回空数据
	if totalCount <= 0 {
		return resp, nil
	}
	// 当前页数没有数据也返回空数据
	if totalCount < ((page - 1) * pageSize) {
		return resp, nil
	}
	if keyword.KeywordKey != "" && keyword.KeywordValue != "" {
		db = db.Where(fmt.Sprintf("%s = ?", keyword.KeywordKey), keyword.KeywordValue)
	}
	offset := int((page - 1) * pageSize)
	if err := db.Offset(offset).Limit(int(pageSize)).Find(&resp.Data).Error; err != nil {
		return nil, err
	}

	return resp, nil
}

func (m PmsProductAttributeValuePagination) Pagination() PmsProductAttributeValuePaginationBasic {
	return PmsProductAttributeValuePaginationBasic{
		CurrentPage: m.CurrentPage,
		PageSize:    m.PageSize,
		TotalPage:   m.TotalPage,
		TotalCount:  m.TotalCount,
	}
}

func (m PmsProductAttributeValuePagination) ToProto(to any, toData any, toPagination any) error {
	if to != nil {
		if err := copier.CopyWithOption(to, m, copier.Option{}); err != nil {
			return err
		}
	}
	if toData != nil {
		if err := copier.Copy(toData, m.Data); err != nil {
			return err
		}
	}
	if toPagination != nil {
		if err := copier.Copy(toPagination, m.Pagination()); err != nil {
			return err
		}
	}
	return nil
}

func (m *defaultPmsProductAttributeValueModel) Insert(ctx context.Context, data *PmsProductAttributeValue) error {
	return m.OrmSession(ctx).Create(data).Error
}

func (m *defaultPmsProductAttributeValueModel) Update(ctx context.Context, data *PmsProductAttributeValue) error {
	if data.Id <= 0 {
		return gorm.ErrMissingWhereClause
	}
	return m.OrmSession(ctx).Where("id = ?", data.Id).Save(data).Error
}
