// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"math"

	"fmt"
	"github.com/jinzhu/copier"
	"gorm.io/gorm"
)

var (
	_ sql.IsolationLevel
)

type (
	pmsProductCategoryAttributeRelationModel interface {
		Insert(ctx context.Context, data *PmsProductCategoryAttributeRelation) error
		FindOne(ctx context.Context, id int64, preloadList ...string) (*PmsProductCategoryAttributeRelation, error)
		OrmSession(ctx context.Context) *gorm.DB
		Transaction(ctx context.Context, fc func(tx *gorm.DB) error, opts ...*sql.TxOptions) error
		FindPageListByBuilder(ormSession *gorm.DB, keyword *KeywordPmsProductCategoryAttributeRelationModel) (*PmsProductCategoryAttributeRelationPagination, error)
		Update(ctx context.Context, data *PmsProductCategoryAttributeRelation) error
		Delete(ctx context.Context, id int64) error
	}

	defaultPmsProductCategoryAttributeRelationModel struct {
		table   string
		ormConn *gorm.DB
	}

	PmsProductCategoryAttributeRelation struct {
		Id                 int64         `json:"id" gorm:"primary_key"`
		ProductCategoryId  sql.NullInt64 `json:"product_category_id"`
		ProductAttributeId sql.NullInt64 `json:"product_attribute_id"`
		PmsProductCategoryAttributeRelationRelation
	}

	PmsProductCategoryAttributeRelationPagination struct {
		Data []*PmsProductCategoryAttributeRelation
		PmsProductCategoryAttributeRelationPaginationBasic
	}

	PmsProductCategoryAttributeRelationPaginationBasic struct {
		CurrentPage int64
		PageSize    int64
		TotalCount  int64
		TotalPage   int64
	}

	KeywordPmsProductCategoryAttributeRelationModel struct {
		KeywordKey     string //like 关键字
		KeywordValue   string //like 值
		Page, PageSize int64
	}
)

func newPmsProductCategoryAttributeRelationModel(db *gorm.DB) *defaultPmsProductCategoryAttributeRelationModel {
	return &defaultPmsProductCategoryAttributeRelationModel{
		table:   "`pms_product_category_attribute_relation`",
		ormConn: db,
	}
}

func (PmsProductCategoryAttributeRelation) TableName() string {
	return "`pms_product_category_attribute_relation`"
}

func (m PmsProductCategoryAttributeRelation) ToProto(toValue interface{}) error {
	return copier.Copy(toValue, &m)
}

func (m *defaultPmsProductCategoryAttributeRelationModel) Delete(ctx context.Context, id int64) error {
	return m.OrmSession(ctx).Delete(&PmsProductCategoryAttributeRelation{}, id).Error
}

func (m *defaultPmsProductCategoryAttributeRelationModel) FindOne(ctx context.Context, id int64, preloadList ...string) (*PmsProductCategoryAttributeRelation, error) {
	var mm PmsProductCategoryAttributeRelation
	db := m.OrmSession(ctx)
	for _, preload := range preloadList {
		db = db.Preload(preload)
	}
	err := db.First(&mm, id).Error
	switch err {
	case nil:
		return &mm, nil
	case gorm.ErrRecordNotFound:
		return nil, gorm.ErrRecordNotFound
	default:
		return nil, err
	}
}

func (m *defaultPmsProductCategoryAttributeRelationModel) OrmSession(ctx context.Context) *gorm.DB {
	return m.ormConn.Model(&PmsProductCategoryAttributeRelation{}).WithContext(ctx)
}

func (m *defaultPmsProductCategoryAttributeRelationModel) Transaction(ctx context.Context, fc func(tx *gorm.DB) error, opts ...*sql.TxOptions) error {
	return m.ormConn.WithContext(ctx).Transaction(fc, opts...)
}

func (m *defaultPmsProductCategoryAttributeRelationModel) FindPageListByBuilder(db *gorm.DB, keyword *KeywordPmsProductCategoryAttributeRelationModel) (*PmsProductCategoryAttributeRelationPagination, error) {
	page := keyword.Page
	pageSize := keyword.PageSize
	// 总行数
	var totalCount int64
	if err := db.Count(&totalCount).Error; err != nil {
		return nil, err
	}
	// 总页数
	totalPage := int64(math.Ceil(float64(totalCount) / float64(pageSize)))

	resp := new(PmsProductCategoryAttributeRelationPagination)
	resp.PageSize = pageSize
	resp.TotalPage = totalPage
	resp.CurrentPage = page
	resp.TotalCount = totalCount

	// 没有数据则返回空数据
	if totalCount <= 0 {
		return resp, nil
	}
	// 当前页数没有数据也返回空数据
	if totalCount < ((page - 1) * pageSize) {
		return resp, nil
	}
	if keyword.KeywordKey != "" && keyword.KeywordValue != "" {
		db = db.Where(fmt.Sprintf("%s = ?", keyword.KeywordKey), keyword.KeywordValue)
	}
	offset := int((page - 1) * pageSize)
	if err := db.Offset(offset).Limit(int(pageSize)).Find(&resp.Data).Error; err != nil {
		return nil, err
	}

	return resp, nil
}

func (m PmsProductCategoryAttributeRelationPagination) Pagination() PmsProductCategoryAttributeRelationPaginationBasic {
	return PmsProductCategoryAttributeRelationPaginationBasic{
		CurrentPage: m.CurrentPage,
		PageSize:    m.PageSize,
		TotalPage:   m.TotalPage,
		TotalCount:  m.TotalCount,
	}
}

func (m PmsProductCategoryAttributeRelationPagination) ToProto(to any, toData any, toPagination any) error {
	if to != nil {
		if err := copier.CopyWithOption(to, m, copier.Option{}); err != nil {
			return err
		}
	}
	if toData != nil {
		if err := copier.Copy(toData, m.Data); err != nil {
			return err
		}
	}
	if toPagination != nil {
		if err := copier.Copy(toPagination, m.Pagination()); err != nil {
			return err
		}
	}
	return nil
}

func (m *defaultPmsProductCategoryAttributeRelationModel) Insert(ctx context.Context, data *PmsProductCategoryAttributeRelation) error {
	return m.OrmSession(ctx).Create(data).Error
}

func (m *defaultPmsProductCategoryAttributeRelationModel) Update(ctx context.Context, data *PmsProductCategoryAttributeRelation) error {
	if data.Id <= 0 {
		return gorm.ErrMissingWhereClause
	}
	return m.OrmSession(ctx).Where("id = ?", data.Id).Save(data).Error
}
