// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"math"

	"fmt"
	"github.com/jinzhu/copier"
	"gorm.io/gorm"
)

var (
	_ sql.IsolationLevel
)

type (
	smsCouponProductRelationModel interface {
		Insert(ctx context.Context, data *SmsCouponProductRelation) error
		FindOne(ctx context.Context, id int64, preloadList ...string) (*SmsCouponProductRelation, error)
		OrmSession(ctx context.Context) *gorm.DB
		Transaction(ctx context.Context, fc func(tx *gorm.DB) error, opts ...*sql.TxOptions) error
		FindPageListByBuilder(ormSession *gorm.DB, keyword *KeywordSmsCouponProductRelationModel) (*SmsCouponProductRelationPagination, error)
		Update(ctx context.Context, data *SmsCouponProductRelation) error
		Delete(ctx context.Context, id int64) error
	}

	defaultSmsCouponProductRelationModel struct {
		table   string
		ormConn *gorm.DB
	}

	SmsCouponProductRelation struct {
		Id          int64          `json:"id" gorm:"primary_key"`
		CouponId    sql.NullInt64  `json:"coupon_id"`
		ProductId   sql.NullInt64  `json:"product_id"`
		ProductName sql.NullString `json:"product_name"` // 商品名称
		ProductSn   sql.NullString `json:"product_sn"`   // 商品编码
		SmsCouponProductRelationRelation
	}

	SmsCouponProductRelationPagination struct {
		Data []*SmsCouponProductRelation
		SmsCouponProductRelationPaginationBasic
	}

	SmsCouponProductRelationPaginationBasic struct {
		CurrentPage int64
		PageSize    int64
		TotalCount  int64
		TotalPage   int64
	}

	KeywordSmsCouponProductRelationModel struct {
		KeywordKey     string //like 关键字
		KeywordValue   string //like 值
		Page, PageSize int64
	}
)

func newSmsCouponProductRelationModel(db *gorm.DB) *defaultSmsCouponProductRelationModel {
	return &defaultSmsCouponProductRelationModel{
		table:   "`sms_coupon_product_relation`",
		ormConn: db,
	}
}

func (SmsCouponProductRelation) TableName() string {
	return "`sms_coupon_product_relation`"
}

func (m SmsCouponProductRelation) ToProto(toValue interface{}) error {
	return copier.Copy(toValue, &m)
}

func (m *defaultSmsCouponProductRelationModel) Delete(ctx context.Context, id int64) error {
	return m.OrmSession(ctx).Delete(&SmsCouponProductRelation{}, id).Error
}

func (m *defaultSmsCouponProductRelationModel) FindOne(ctx context.Context, id int64, preloadList ...string) (*SmsCouponProductRelation, error) {
	var mm SmsCouponProductRelation
	db := m.OrmSession(ctx)
	for _, preload := range preloadList {
		db = db.Preload(preload)
	}
	err := db.First(&mm, id).Error
	switch err {
	case nil:
		return &mm, nil
	case gorm.ErrRecordNotFound:
		return nil, gorm.ErrRecordNotFound
	default:
		return nil, err
	}
}

func (m *defaultSmsCouponProductRelationModel) OrmSession(ctx context.Context) *gorm.DB {
	return m.ormConn.Model(&SmsCouponProductRelation{}).WithContext(ctx)
}

func (m *defaultSmsCouponProductRelationModel) Transaction(ctx context.Context, fc func(tx *gorm.DB) error, opts ...*sql.TxOptions) error {
	return m.ormConn.WithContext(ctx).Transaction(fc, opts...)
}

func (m *defaultSmsCouponProductRelationModel) FindPageListByBuilder(db *gorm.DB, keyword *KeywordSmsCouponProductRelationModel) (*SmsCouponProductRelationPagination, error) {
	page := keyword.Page
	pageSize := keyword.PageSize
	// 总行数
	var totalCount int64
	if err := db.Count(&totalCount).Error; err != nil {
		return nil, err
	}
	// 总页数
	totalPage := int64(math.Ceil(float64(totalCount) / float64(pageSize)))

	resp := new(SmsCouponProductRelationPagination)
	resp.PageSize = pageSize
	resp.TotalPage = totalPage
	resp.CurrentPage = page
	resp.TotalCount = totalCount

	// 没有数据则返回空数据
	if totalCount <= 0 {
		return resp, nil
	}
	// 当前页数没有数据也返回空数据
	if totalCount < ((page - 1) * pageSize) {
		return resp, nil
	}
	if keyword.KeywordKey != "" && keyword.KeywordValue != "" {
		db = db.Where(fmt.Sprintf("%s = ?", keyword.KeywordKey), keyword.KeywordValue)
	}
	offset := int((page - 1) * pageSize)
	if err := db.Offset(offset).Limit(int(pageSize)).Find(&resp.Data).Error; err != nil {
		return nil, err
	}

	return resp, nil
}

func (m SmsCouponProductRelationPagination) Pagination() SmsCouponProductRelationPaginationBasic {
	return SmsCouponProductRelationPaginationBasic{
		CurrentPage: m.CurrentPage,
		PageSize:    m.PageSize,
		TotalPage:   m.TotalPage,
		TotalCount:  m.TotalCount,
	}
}

func (m SmsCouponProductRelationPagination) ToProto(to any, toData any, toPagination any) error {
	if to != nil {
		if err := copier.CopyWithOption(to, m, copier.Option{}); err != nil {
			return err
		}
	}
	if toData != nil {
		if err := copier.Copy(toData, m.Data); err != nil {
			return err
		}
	}
	if toPagination != nil {
		if err := copier.Copy(toPagination, m.Pagination()); err != nil {
			return err
		}
	}
	return nil
}

func (m *defaultSmsCouponProductRelationModel) Insert(ctx context.Context, data *SmsCouponProductRelation) error {
	return m.OrmSession(ctx).Create(data).Error
}

func (m *defaultSmsCouponProductRelationModel) Update(ctx context.Context, data *SmsCouponProductRelation) error {
	if data.Id <= 0 {
		return gorm.ErrMissingWhereClause
	}
	return m.OrmSession(ctx).Where("id = ?", data.Id).Save(data).Error
}
