// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"math"

	"github.com/jinzhu/copier"
	"gorm.io/gorm"
)

var (
	_ sql.IsolationLevel
)

type (
	smsFlashPromotionSessionModel interface {
		Insert(ctx context.Context, data *SmsFlashPromotionSession) error
		FindOne(ctx context.Context, id int64, preloadList ...string) (*SmsFlashPromotionSession, error)
		OrmSession(ctx context.Context) *gorm.DB
		Transaction(ctx context.Context, fc func(tx *gorm.DB) error, opts ...*sql.TxOptions) error
		FindPageListByBuilder(ormSession *gorm.DB, keyword *KeywordSmsFlashPromotionSessionModel) (*SmsFlashPromotionSessionPagination, error)
		Update(ctx context.Context, data *SmsFlashPromotionSession) error
		Delete(ctx context.Context, id int64) error
	}

	defaultSmsFlashPromotionSessionModel struct {
		table   string
		ormConn *gorm.DB
	}

	SmsFlashPromotionSession struct {
		Id         int64          `json:"id" gorm:"primary_key"` // 编号
		Name       sql.NullString `json:"name"`                  // 场次名称
		StartTime  sql.NullString `json:"start_time"`            // 每日开始时间
		EndTime    sql.NullString `json:"end_time"`              // 每日结束时间
		Status     sql.NullInt64  `json:"status"`                // 启用状态：0->不启用；1->启用
		CreateTime sql.NullTime   `json:"create_time"`           // 创建时间
		SmsFlashPromotionSessionRelation
	}

	SmsFlashPromotionSessionPagination struct {
		Data []*SmsFlashPromotionSession
		SmsFlashPromotionSessionPaginationBasic
	}

	SmsFlashPromotionSessionPaginationBasic struct {
		CurrentPage int64
		PageSize    int64
		TotalCount  int64
		TotalPage   int64
	}

	KeywordSmsFlashPromotionSessionModel struct {
		KeywordKey     string //like 关键字
		KeywordValue   string //like 值
		Page, PageSize int64
	}
)

func newSmsFlashPromotionSessionModel(db *gorm.DB) *defaultSmsFlashPromotionSessionModel {
	return &defaultSmsFlashPromotionSessionModel{
		table:   "`sms_flash_promotion_session`",
		ormConn: db,
	}
}

func (SmsFlashPromotionSession) TableName() string {
	return "`sms_flash_promotion_session`"
}

func (m SmsFlashPromotionSession) ToProto(toValue interface{}) error {
	return copier.Copy(toValue, &m)
}

func (m *defaultSmsFlashPromotionSessionModel) Delete(ctx context.Context, id int64) error {
	return m.OrmSession(ctx).Delete(&SmsFlashPromotionSession{}, id).Error
}

func (m *defaultSmsFlashPromotionSessionModel) FindOne(ctx context.Context, id int64, preloadList ...string) (*SmsFlashPromotionSession, error) {
	var mm SmsFlashPromotionSession
	db := m.OrmSession(ctx)
	for _, preload := range preloadList {
		db = db.Preload(preload)
	}
	err := db.First(&mm, id).Error
	switch err {
	case nil:
		return &mm, nil
	case gorm.ErrRecordNotFound:
		return nil, gorm.ErrRecordNotFound
	default:
		return nil, err
	}
}

func (m *defaultSmsFlashPromotionSessionModel) OrmSession(ctx context.Context) *gorm.DB {
	return m.ormConn.Model(&SmsFlashPromotionSession{}).WithContext(ctx)
}

func (m *defaultSmsFlashPromotionSessionModel) Transaction(ctx context.Context, fc func(tx *gorm.DB) error, opts ...*sql.TxOptions) error {
	return m.ormConn.WithContext(ctx).Transaction(fc, opts...)
}

func (m *defaultSmsFlashPromotionSessionModel) FindPageListByBuilder(db *gorm.DB, keyword *KeywordSmsFlashPromotionSessionModel) (*SmsFlashPromotionSessionPagination, error) {
	page := keyword.Page
	pageSize := keyword.PageSize
	// 总行数
	var totalCount int64
	if err := db.Count(&totalCount).Error; err != nil {
		return nil, err
	}
	// 总页数
	totalPage := int64(math.Ceil(float64(totalCount) / float64(pageSize)))

	resp := new(SmsFlashPromotionSessionPagination)
	resp.PageSize = pageSize
	resp.TotalPage = totalPage
	resp.CurrentPage = page
	resp.TotalCount = totalCount

	// 没有数据则返回空数据
	if totalCount <= 0 {
		return resp, nil
	}
	// 当前页数没有数据也返回空数据
	if totalCount < ((page - 1) * pageSize) {
		return resp, nil
	}
	if keyword.KeywordKey != "" && keyword.KeywordValue != "" {
		db = db.Where(fmt.Sprintf("%s = ?", keyword.KeywordKey), keyword.KeywordValue)
	}
	offset := int((page - 1) * pageSize)
	if err := db.Offset(offset).Limit(int(pageSize)).Find(&resp.Data).Error; err != nil {
		return nil, err
	}

	return resp, nil
}

func (m SmsFlashPromotionSessionPagination) Pagination() SmsFlashPromotionSessionPaginationBasic {
	return SmsFlashPromotionSessionPaginationBasic{
		CurrentPage: m.CurrentPage,
		PageSize:    m.PageSize,
		TotalPage:   m.TotalPage,
		TotalCount:  m.TotalCount,
	}
}

func (m SmsFlashPromotionSessionPagination) ToProto(to any, toData any, toPagination any) error {
	if to != nil {
		if err := copier.CopyWithOption(to, m, copier.Option{}); err != nil {
			return err
		}
	}
	if toData != nil {
		if err := copier.Copy(toData, m.Data); err != nil {
			return err
		}
	}
	if toPagination != nil {
		if err := copier.Copy(toPagination, m.Pagination()); err != nil {
			return err
		}
	}
	return nil
}

func (m *defaultSmsFlashPromotionSessionModel) Insert(ctx context.Context, data *SmsFlashPromotionSession) error {
	return m.OrmSession(ctx).Create(data).Error
}

func (m *defaultSmsFlashPromotionSessionModel) Update(ctx context.Context, data *SmsFlashPromotionSession) error {
	if data.Id <= 0 {
		return gorm.ErrMissingWhereClause
	}
	return m.OrmSession(ctx).Where("id = ?", data.Id).Save(data).Error
}
