// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"math"

	"fmt"
	"github.com/jinzhu/copier"
	"gorm.io/gorm"
)

var (
	_ sql.IsolationLevel
)

type (
	smsHomeAdvertiseModel interface {
		Insert(ctx context.Context, data *SmsHomeAdvertise) error
		FindOne(ctx context.Context, id int64, preloadList ...string) (*SmsHomeAdvertise, error)
		OrmSession(ctx context.Context) *gorm.DB
		Transaction(ctx context.Context, fc func(tx *gorm.DB) error, opts ...*sql.TxOptions) error
		FindPageListByBuilder(ormSession *gorm.DB, keyword *KeywordSmsHomeAdvertiseModel) (*SmsHomeAdvertisePagination, error)
		Update(ctx context.Context, data *SmsHomeAdvertise) error
		Delete(ctx context.Context, id int64) error
	}

	defaultSmsHomeAdvertiseModel struct {
		table   string
		ormConn *gorm.DB
	}

	SmsHomeAdvertise struct {
		Id         int64          `json:"id" gorm:"primary_key"`
		Name       sql.NullString `json:"name"`
		Type       sql.NullInt64  `json:"type"` // 轮播位置：0->PC首页轮播；1->app首页轮播
		Pic        sql.NullString `json:"pic"`
		StartTime  sql.NullTime   `json:"start_time"`
		EndTime    sql.NullTime   `json:"end_time"`
		Status     sql.NullInt64  `json:"status"`      // 上下线状态：0->下线；1->上线
		ClickCount sql.NullInt64  `json:"click_count"` // 点击数
		OrderCount sql.NullInt64  `json:"order_count"` // 下单数
		Url        sql.NullString `json:"url"`         // 链接地址
		Note       sql.NullString `json:"note"`        // 备注
		Sort       int64          `json:"sort"`        // 排序
		SmsHomeAdvertiseRelation
	}

	SmsHomeAdvertisePagination struct {
		Data []*SmsHomeAdvertise
		SmsHomeAdvertisePaginationBasic
	}

	SmsHomeAdvertisePaginationBasic struct {
		CurrentPage int64
		PageSize    int64
		TotalCount  int64
		TotalPage   int64
	}

	KeywordSmsHomeAdvertiseModel struct {
		KeywordKey     string //like 关键字
		KeywordValue   string //like 值
		Page, PageSize int64
	}
)

func newSmsHomeAdvertiseModel(db *gorm.DB) *defaultSmsHomeAdvertiseModel {
	return &defaultSmsHomeAdvertiseModel{
		table:   "`sms_home_advertise`",
		ormConn: db,
	}
}

func (SmsHomeAdvertise) TableName() string {
	return "`sms_home_advertise`"
}

func (m SmsHomeAdvertise) ToProto(toValue interface{}) error {
	return copier.Copy(toValue, &m)
}

func (m *defaultSmsHomeAdvertiseModel) Delete(ctx context.Context, id int64) error {
	return m.OrmSession(ctx).Delete(&SmsHomeAdvertise{}, id).Error
}

func (m *defaultSmsHomeAdvertiseModel) FindOne(ctx context.Context, id int64, preloadList ...string) (*SmsHomeAdvertise, error) {
	var mm SmsHomeAdvertise
	db := m.OrmSession(ctx)
	for _, preload := range preloadList {
		db = db.Preload(preload)
	}
	err := db.First(&mm, id).Error
	switch err {
	case nil:
		return &mm, nil
	case gorm.ErrRecordNotFound:
		return nil, gorm.ErrRecordNotFound
	default:
		return nil, err
	}
}

func (m *defaultSmsHomeAdvertiseModel) OrmSession(ctx context.Context) *gorm.DB {
	return m.ormConn.Model(&SmsHomeAdvertise{}).WithContext(ctx)
}

func (m *defaultSmsHomeAdvertiseModel) Transaction(ctx context.Context, fc func(tx *gorm.DB) error, opts ...*sql.TxOptions) error {
	return m.ormConn.WithContext(ctx).Transaction(fc, opts...)
}

func (m *defaultSmsHomeAdvertiseModel) FindPageListByBuilder(db *gorm.DB, keyword *KeywordSmsHomeAdvertiseModel) (*SmsHomeAdvertisePagination, error) {
	page := keyword.Page
	pageSize := keyword.PageSize
	// 总行数
	var totalCount int64
	if err := db.Count(&totalCount).Error; err != nil {
		return nil, err
	}
	// 总页数
	totalPage := int64(math.Ceil(float64(totalCount) / float64(pageSize)))

	resp := new(SmsHomeAdvertisePagination)
	resp.PageSize = pageSize
	resp.TotalPage = totalPage
	resp.CurrentPage = page
	resp.TotalCount = totalCount

	// 没有数据则返回空数据
	if totalCount <= 0 {
		return resp, nil
	}
	// 当前页数没有数据也返回空数据
	if totalCount < ((page - 1) * pageSize) {
		return resp, nil
	}
	if keyword.KeywordKey != "" && keyword.KeywordValue != "" {
		db = db.Where(fmt.Sprintf("%s = ?", keyword.KeywordKey), keyword.KeywordValue)
	}
	offset := int((page - 1) * pageSize)
	if err := db.Offset(offset).Limit(int(pageSize)).Find(&resp.Data).Error; err != nil {
		return nil, err
	}

	return resp, nil
}

func (m SmsHomeAdvertisePagination) Pagination() SmsHomeAdvertisePaginationBasic {
	return SmsHomeAdvertisePaginationBasic{
		CurrentPage: m.CurrentPage,
		PageSize:    m.PageSize,
		TotalPage:   m.TotalPage,
		TotalCount:  m.TotalCount,
	}
}

func (m SmsHomeAdvertisePagination) ToProto(to any, toData any, toPagination any) error {
	if to != nil {
		if err := copier.CopyWithOption(to, m, copier.Option{}); err != nil {
			return err
		}
	}
	if toData != nil {
		if err := copier.Copy(toData, m.Data); err != nil {
			return err
		}
	}
	if toPagination != nil {
		if err := copier.Copy(toPagination, m.Pagination()); err != nil {
			return err
		}
	}
	return nil
}

func (m *defaultSmsHomeAdvertiseModel) Insert(ctx context.Context, data *SmsHomeAdvertise) error {
	return m.OrmSession(ctx).Create(data).Error
}

func (m *defaultSmsHomeAdvertiseModel) Update(ctx context.Context, data *SmsHomeAdvertise) error {
	if data.Id <= 0 {
		return gorm.ErrMissingWhereClause
	}
	return m.OrmSession(ctx).Where("id = ?", data.Id).Save(data).Error
}
