// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"math"

	"github.com/jinzhu/copier"
	"gorm.io/gorm"
)

var (
	_ sql.IsolationLevel
)

type (
	smsCouponHistoryModel interface {
		Insert(ctx context.Context, data *SmsCouponHistory) error
		FindOne(ctx context.Context, id int64, preloadList ...string) (*SmsCouponHistory, error)
		OrmSession(ctx context.Context) *gorm.DB
		Transaction(ctx context.Context, fc func(tx *gorm.DB) error, opts ...*sql.TxOptions) error
		FindPageListByBuilder(ormSession *gorm.DB, keyword *KeywordSmsCouponHistoryModel) (*SmsCouponHistoryPagination, error)
		Update(ctx context.Context, data *SmsCouponHistory) error
		Delete(ctx context.Context, id int64) error
	}

	defaultSmsCouponHistoryModel struct {
		table   string
		ormConn *gorm.DB
	}

	SmsCouponHistory struct {
		Id             int64          `json:"id" gorm:"primary_key"`
		CouponId       sql.NullInt64  `json:"coupon_id"`
		MemberId       sql.NullInt64  `json:"member_id"`
		CouponCode     sql.NullString `json:"coupon_code"`
		MemberNickname sql.NullString `json:"member_nickname"` // 领取人昵称
		GetType        sql.NullInt64  `json:"get_type"`        // 获取类型：0->后台赠送；1->主动获取
		CreateTime     sql.NullTime   `json:"create_time"`
		UseStatus      sql.NullInt64  `json:"use_status"` // 使用状态：0->未使用；1->已使用；2->已过期
		UseTime        sql.NullTime   `json:"use_time"`   // 使用时间
		OrderId        sql.NullInt64  `json:"order_id"`   // 订单编号
		OrderSn        sql.NullString `json:"order_sn"`   // 订单号码
		SmsCouponHistoryRelation
	}

	SmsCouponHistoryPagination struct {
		Data []*SmsCouponHistory
		SmsCouponHistoryPaginationBasic
	}

	SmsCouponHistoryPaginationBasic struct {
		CurrentPage int64
		PageSize    int64
		TotalCount  int64
		TotalPage   int64
	}

	KeywordSmsCouponHistoryModel struct {
		KeywordKey     string //like 关键字
		KeywordValue   string //like 值
		Page, PageSize int64
	}
)

func newSmsCouponHistoryModel(db *gorm.DB) *defaultSmsCouponHistoryModel {
	return &defaultSmsCouponHistoryModel{
		table:   "`sms_coupon_history`",
		ormConn: db,
	}
}

func (SmsCouponHistory) TableName() string {
	return "`sms_coupon_history`"
}

func (m SmsCouponHistory) ToProto(toValue interface{}) error {
	return copier.Copy(toValue, &m)
}

func (m *defaultSmsCouponHistoryModel) Delete(ctx context.Context, id int64) error {
	return m.OrmSession(ctx).Delete(&SmsCouponHistory{}, id).Error
}

func (m *defaultSmsCouponHistoryModel) FindOne(ctx context.Context, id int64, preloadList ...string) (*SmsCouponHistory, error) {
	var mm SmsCouponHistory
	db := m.OrmSession(ctx)
	for _, preload := range preloadList {
		db = db.Preload(preload)
	}
	err := db.First(&mm, id).Error
	switch err {
	case nil:
		return &mm, nil
	case gorm.ErrRecordNotFound:
		return nil, gorm.ErrRecordNotFound
	default:
		return nil, err
	}
}

func (m *defaultSmsCouponHistoryModel) OrmSession(ctx context.Context) *gorm.DB {
	return m.ormConn.Model(&SmsCouponHistory{}).WithContext(ctx)
}

func (m *defaultSmsCouponHistoryModel) Transaction(ctx context.Context, fc func(tx *gorm.DB) error, opts ...*sql.TxOptions) error {
	return m.ormConn.WithContext(ctx).Transaction(fc, opts...)
}

func (m *defaultSmsCouponHistoryModel) FindPageListByBuilder(db *gorm.DB, keyword *KeywordSmsCouponHistoryModel) (*SmsCouponHistoryPagination, error) {
	page := keyword.Page
	pageSize := keyword.PageSize
	// 总行数
	var totalCount int64
	if err := db.Count(&totalCount).Error; err != nil {
		return nil, err
	}
	// 总页数
	totalPage := int64(math.Ceil(float64(totalCount) / float64(pageSize)))

	resp := new(SmsCouponHistoryPagination)
	resp.PageSize = pageSize
	resp.TotalPage = totalPage
	resp.CurrentPage = page
	resp.TotalCount = totalCount

	// 没有数据则返回空数据
	if totalCount <= 0 {
		return resp, nil
	}
	// 当前页数没有数据也返回空数据
	if totalCount < ((page - 1) * pageSize) {
		return resp, nil
	}
	if keyword.KeywordKey != "" && keyword.KeywordValue != "" {
		db = db.Where(fmt.Sprintf("%s = ?", keyword.KeywordKey), keyword.KeywordValue)
	}
	offset := int((page - 1) * pageSize)
	if err := db.Offset(offset).Limit(int(pageSize)).Find(&resp.Data).Error; err != nil {
		return nil, err
	}

	return resp, nil
}

func (m SmsCouponHistoryPagination) Pagination() SmsCouponHistoryPaginationBasic {
	return SmsCouponHistoryPaginationBasic{
		CurrentPage: m.CurrentPage,
		PageSize:    m.PageSize,
		TotalPage:   m.TotalPage,
		TotalCount:  m.TotalCount,
	}
}

func (m SmsCouponHistoryPagination) ToProto(to any, toData any, toPagination any) error {
	if to != nil {
		if err := copier.CopyWithOption(to, m, copier.Option{}); err != nil {
			return err
		}
	}
	if toData != nil {
		if err := copier.Copy(toData, m.Data); err != nil {
			return err
		}
	}
	if toPagination != nil {
		if err := copier.Copy(toPagination, m.Pagination()); err != nil {
			return err
		}
	}
	return nil
}

func (m *defaultSmsCouponHistoryModel) Insert(ctx context.Context, data *SmsCouponHistory) error {
	return m.OrmSession(ctx).Create(data).Error
}

func (m *defaultSmsCouponHistoryModel) Update(ctx context.Context, data *SmsCouponHistory) error {
	if data.Id <= 0 {
		return gorm.ErrMissingWhereClause
	}
	return m.OrmSession(ctx).Where("id = ?", data.Id).Save(data).Error
}
