// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"math"

	"fmt"
	"github.com/jinzhu/copier"
	"gorm.io/gorm"
)

var (
	_ sql.IsolationLevel
)

type (
	smsHomeNewProductModel interface {
		Insert(ctx context.Context, data *SmsHomeNewProduct) error
		FindOne(ctx context.Context, id int64, preloadList ...string) (*SmsHomeNewProduct, error)
		OrmSession(ctx context.Context) *gorm.DB
		Transaction(ctx context.Context, fc func(tx *gorm.DB) error, opts ...*sql.TxOptions) error
		FindPageListByBuilder(ctx context.Context, keyword *KeywordSmsHomeNewProductModel) (*SmsHomeNewProductPagination, error)
		Update(ctx context.Context, data *SmsHomeNewProduct) error
		Delete(ctx context.Context, id int64) error
	}

	defaultSmsHomeNewProductModel struct {
		table   string
		ormConn *gorm.DB
	}

	SmsHomeNewProduct struct {
		Id              int64          `json:"id" gorm:"primary_key"`
		ProductId       sql.NullInt64  `json:"product_id"`
		ProductName     sql.NullString `json:"product_name"`
		RecommendStatus sql.NullInt64  `json:"recommend_status"`
		Sort            sql.NullInt64  `json:"sort"`
		SmsHomeNewProductRelation
	}

	SmsHomeNewProductPagination struct {
		Data []*SmsHomeNewProduct
		SmsHomeNewProductPaginationBasic
	}

	SmsHomeNewProductPaginationBasic struct {
		CurrentPage int64
		PageSize    int64
		TotalCount  int64
		TotalPage   int64
	}

	KeywordSmsHomeNewProductModel struct {
		KeywordKey     string //like 关键字
		KeywordValue   string //like 值
		Page, PageSize int64
	}
)

func newSmsHomeNewProductModel(db *gorm.DB) *defaultSmsHomeNewProductModel {
	return &defaultSmsHomeNewProductModel{
		table:   "`sms_home_new_product`",
		ormConn: db,
	}
}

func (SmsHomeNewProduct) TableName() string {
	return "`sms_home_new_product`"
}

func (m SmsHomeNewProduct) ToProto(toValue interface{}) error {
	return copier.Copy(toValue, &m)
}

func (m *defaultSmsHomeNewProductModel) Delete(ctx context.Context, id int64) error {
	return m.OrmSession(ctx).Delete(&SmsHomeNewProduct{}, id).Error
}

func (m *defaultSmsHomeNewProductModel) FindOne(ctx context.Context, id int64, preloadList ...string) (*SmsHomeNewProduct, error) {
	var mm SmsHomeNewProduct
	db := m.OrmSession(ctx)
	for _, preload := range preloadList {
		db = db.Preload(preload)
	}
	err := db.First(&mm, id).Error
	switch err {
	case nil:
		return &mm, nil
	case gorm.ErrRecordNotFound:
		return nil, gorm.ErrRecordNotFound
	default:
		return nil, err
	}
}

func (m *defaultSmsHomeNewProductModel) OrmSession(ctx context.Context) *gorm.DB {
	return m.ormConn.Model(&SmsHomeNewProduct{}).WithContext(ctx)
}

func (m *defaultSmsHomeNewProductModel) Transaction(ctx context.Context, fc func(tx *gorm.DB) error, opts ...*sql.TxOptions) error {
	return m.ormConn.WithContext(ctx).Transaction(fc, opts...)
}

func (m *defaultSmsHomeNewProductModel) FindPageListByBuilder(ctx context.Context, keyword *KeywordSmsHomeNewProductModel) (*SmsHomeNewProductPagination, error) {
	page := keyword.Page
	pageSize := keyword.PageSize
	// 总行数
	var totalCount int64
	db := m.OrmSession(ctx)
	if err := db.Count(&totalCount).Error; err != nil {
		return nil, err
	}
	// 总页数
	totalPage := int64(math.Ceil(float64(totalCount) / float64(pageSize)))

	resp := new(SmsHomeNewProductPagination)
	resp.PageSize = pageSize
	resp.TotalPage = totalPage
	resp.CurrentPage = page
	resp.TotalCount = totalCount

	// 没有数据则返回空数据
	if totalCount <= 0 {
		return resp, nil
	}
	// 当前页数没有数据也返回空数据
	if totalCount < ((page - 1) * pageSize) {
		return resp, nil
	}
	if keyword.KeywordKey != "" && keyword.KeywordValue != "" {
		db = db.Where(fmt.Sprintf("%s = ?", keyword.KeywordKey), keyword.KeywordValue)
	}
	offset := int((page - 1) * pageSize)
	if err := db.Offset(offset).Limit(int(pageSize)).Find(&resp.Data).Error; err != nil {
		return nil, err
	}

	return resp, nil
}

func (m SmsHomeNewProductPagination) Pagination() SmsHomeNewProductPaginationBasic {
	return SmsHomeNewProductPaginationBasic{
		CurrentPage: m.CurrentPage,
		PageSize:    m.PageSize,
		TotalPage:   m.TotalPage,
		TotalCount:  m.TotalCount,
	}
}

func (m SmsHomeNewProductPagination) ToProto(to any, toData any, toPagination any) error {
	if to != nil {
		if err := copier.CopyWithOption(to, m, copier.Option{}); err != nil {
			return err
		}
	}
	if toData != nil {
		if err := copier.Copy(toData, m.Data); err != nil {
			return err
		}
	}
	if toPagination != nil {
		if err := copier.Copy(toPagination, m.Pagination()); err != nil {
			return err
		}
	}
	return nil
}

func (m *defaultSmsHomeNewProductModel) Insert(ctx context.Context, data *SmsHomeNewProduct) error {
	return m.OrmSession(ctx).Create(data).Error
}

func (m *defaultSmsHomeNewProductModel) Update(ctx context.Context, data *SmsHomeNewProduct) error {
	if data.Id <= 0 {
		return gorm.ErrMissingWhereClause
	}
	return m.OrmSession(ctx).Where("id = ?", data.Id).Save(data).Error
}
