// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"math"

	"fmt"
	"github.com/jinzhu/copier"
	"gorm.io/gorm"
)

var (
	_ sql.IsolationLevel
)

type (
	umsMemberTagModel interface {
		Insert(ctx context.Context, data *UmsMemberTag) error
		FindOne(ctx context.Context, id int64, preloadList ...string) (*UmsMemberTag, error)
		OrmSession(ctx context.Context) *gorm.DB
		Transaction(ctx context.Context, fc func(tx *gorm.DB) error, opts ...*sql.TxOptions) error
		FindPageListByBuilder(ormSession *gorm.DB, keyword *KeywordUmsMemberTagModel) (*UmsMemberTagPagination, error)
		Update(ctx context.Context, data *UmsMemberTag) error
		Delete(ctx context.Context, id int64) error
	}

	defaultUmsMemberTagModel struct {
		table   string
		ormConn *gorm.DB
	}

	UmsMemberTag struct {
		Id                int64           `json:"id" gorm:"primary_key"`
		Name              sql.NullString  `json:"name"`
		FinishOrderCount  sql.NullInt64   `json:"finish_order_count"`  // 自动打标签完成订单数量
		FinishOrderAmount sql.NullFloat64 `json:"finish_order_amount"` // 自动打标签完成订单金额
		UmsMemberTagRelation
	}

	UmsMemberTagPagination struct {
		Data []*UmsMemberTag
		UmsMemberTagPaginationBasic
	}

	UmsMemberTagPaginationBasic struct {
		CurrentPage int64
		PageSize    int64
		TotalCount  int64
		TotalPage   int64
	}

	KeywordUmsMemberTagModel struct {
		KeywordKey     string //like 关键字
		KeywordValue   string //like 值
		Page, PageSize int64
	}
)

func newUmsMemberTagModel(db *gorm.DB) *defaultUmsMemberTagModel {
	return &defaultUmsMemberTagModel{
		table:   "`ums_member_tag`",
		ormConn: db,
	}
}

func (UmsMemberTag) TableName() string {
	return "`ums_member_tag`"
}

func (m UmsMemberTag) ToProto(toValue interface{}) error {
	return copier.Copy(toValue, &m)
}

func (m *defaultUmsMemberTagModel) Delete(ctx context.Context, id int64) error {
	return m.OrmSession(ctx).Delete(&UmsMemberTag{}, id).Error
}

func (m *defaultUmsMemberTagModel) FindOne(ctx context.Context, id int64, preloadList ...string) (*UmsMemberTag, error) {
	var mm UmsMemberTag
	db := m.OrmSession(ctx)
	for _, preload := range preloadList {
		db = db.Preload(preload)
	}
	err := db.First(&mm, id).Error
	switch err {
	case nil:
		return &mm, nil
	case gorm.ErrRecordNotFound:
		return nil, gorm.ErrRecordNotFound
	default:
		return nil, err
	}
}

func (m *defaultUmsMemberTagModel) OrmSession(ctx context.Context) *gorm.DB {
	return m.ormConn.Model(&UmsMemberTag{}).WithContext(ctx)
}

func (m *defaultUmsMemberTagModel) Transaction(ctx context.Context, fc func(tx *gorm.DB) error, opts ...*sql.TxOptions) error {
	return m.ormConn.WithContext(ctx).Transaction(fc, opts...)
}

func (m *defaultUmsMemberTagModel) FindPageListByBuilder(db *gorm.DB, keyword *KeywordUmsMemberTagModel) (*UmsMemberTagPagination, error) {
	page := keyword.Page
	pageSize := keyword.PageSize
	// 总行数
	var totalCount int64
	if err := db.Count(&totalCount).Error; err != nil {
		return nil, err
	}
	// 总页数
	totalPage := int64(math.Ceil(float64(totalCount) / float64(pageSize)))

	resp := new(UmsMemberTagPagination)
	resp.PageSize = pageSize
	resp.TotalPage = totalPage
	resp.CurrentPage = page
	resp.TotalCount = totalCount

	// 没有数据则返回空数据
	if totalCount <= 0 {
		return resp, nil
	}
	// 当前页数没有数据也返回空数据
	if totalCount < ((page - 1) * pageSize) {
		return resp, nil
	}
	if keyword.KeywordKey != "" && keyword.KeywordValue != "" {
		db = db.Where(fmt.Sprintf("%s = ?", keyword.KeywordKey), keyword.KeywordValue)
	}
	offset := int((page - 1) * pageSize)
	if err := db.Offset(offset).Limit(int(pageSize)).Find(&resp.Data).Error; err != nil {
		return nil, err
	}

	return resp, nil
}

func (m UmsMemberTagPagination) Pagination() UmsMemberTagPaginationBasic {
	return UmsMemberTagPaginationBasic{
		CurrentPage: m.CurrentPage,
		PageSize:    m.PageSize,
		TotalPage:   m.TotalPage,
		TotalCount:  m.TotalCount,
	}
}

func (m UmsMemberTagPagination) ToProto(to any, toData any, toPagination any) error {
	if to != nil {
		if err := copier.CopyWithOption(to, m, copier.Option{}); err != nil {
			return err
		}
	}
	if toData != nil {
		if err := copier.Copy(toData, m.Data); err != nil {
			return err
		}
	}
	if toPagination != nil {
		if err := copier.Copy(toPagination, m.Pagination()); err != nil {
			return err
		}
	}
	return nil
}

func (m *defaultUmsMemberTagModel) Insert(ctx context.Context, data *UmsMemberTag) error {
	return m.OrmSession(ctx).Create(data).Error
}

func (m *defaultUmsMemberTagModel) Update(ctx context.Context, data *UmsMemberTag) error {
	if data.Id <= 0 {
		return gorm.ErrMissingWhereClause
	}
	return m.OrmSession(ctx).Where("id = ?", data.Id).Save(data).Error
}
