// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"math"

	"fmt"
	"github.com/jinzhu/copier"
	"gorm.io/gorm"
)

var (
	_ sql.IsolationLevel
)

type (
	umsMemberTaskModel interface {
		Insert(ctx context.Context, data *UmsMemberTask) error
		FindOne(ctx context.Context, id int64, preloadList ...string) (*UmsMemberTask, error)
		OrmSession(ctx context.Context) *gorm.DB
		Transaction(ctx context.Context, fc func(tx *gorm.DB) error, opts ...*sql.TxOptions) error
		FindPageListByBuilder(ormSession *gorm.DB, keyword *KeywordUmsMemberTaskModel) (*UmsMemberTaskPagination, error)
		Update(ctx context.Context, data *UmsMemberTask) error
		Delete(ctx context.Context, id int64) error
	}

	defaultUmsMemberTaskModel struct {
		table   string
		ormConn *gorm.DB
	}

	UmsMemberTask struct {
		Id           int64          `json:"id" gorm:"primary_key"`
		Name         sql.NullString `json:"name"`
		Growth       sql.NullInt64  `json:"growth"`       // 赠送成长值
		Intergration sql.NullInt64  `json:"intergration"` // 赠送积分
		Type         sql.NullInt64  `json:"type"`         // 任务类型：0->新手任务；1->日常任务
		UmsMemberTaskRelation
	}

	UmsMemberTaskPagination struct {
		Data []*UmsMemberTask
		UmsMemberTaskPaginationBasic
	}

	UmsMemberTaskPaginationBasic struct {
		CurrentPage int64
		PageSize    int64
		TotalCount  int64
		TotalPage   int64
	}

	KeywordUmsMemberTaskModel struct {
		KeywordKey     string //like 关键字
		KeywordValue   string //like 值
		Page, PageSize int64
	}
)

func newUmsMemberTaskModel(db *gorm.DB) *defaultUmsMemberTaskModel {
	return &defaultUmsMemberTaskModel{
		table:   "`ums_member_task`",
		ormConn: db,
	}
}

func (UmsMemberTask) TableName() string {
	return "`ums_member_task`"
}

func (m UmsMemberTask) ToProto(toValue interface{}) error {
	return copier.Copy(toValue, &m)
}

func (m *defaultUmsMemberTaskModel) Delete(ctx context.Context, id int64) error {
	return m.OrmSession(ctx).Delete(&UmsMemberTask{}, id).Error
}

func (m *defaultUmsMemberTaskModel) FindOne(ctx context.Context, id int64, preloadList ...string) (*UmsMemberTask, error) {
	var mm UmsMemberTask
	db := m.OrmSession(ctx)
	for _, preload := range preloadList {
		db = db.Preload(preload)
	}
	err := db.First(&mm, id).Error
	switch err {
	case nil:
		return &mm, nil
	case gorm.ErrRecordNotFound:
		return nil, gorm.ErrRecordNotFound
	default:
		return nil, err
	}
}

func (m *defaultUmsMemberTaskModel) OrmSession(ctx context.Context) *gorm.DB {
	return m.ormConn.Model(&UmsMemberTask{}).WithContext(ctx)
}

func (m *defaultUmsMemberTaskModel) Transaction(ctx context.Context, fc func(tx *gorm.DB) error, opts ...*sql.TxOptions) error {
	return m.ormConn.WithContext(ctx).Transaction(fc, opts...)
}

func (m *defaultUmsMemberTaskModel) FindPageListByBuilder(db *gorm.DB, keyword *KeywordUmsMemberTaskModel) (*UmsMemberTaskPagination, error) {
	page := keyword.Page
	pageSize := keyword.PageSize
	// 总行数
	var totalCount int64
	if err := db.Count(&totalCount).Error; err != nil {
		return nil, err
	}
	// 总页数
	totalPage := int64(math.Ceil(float64(totalCount) / float64(pageSize)))

	resp := new(UmsMemberTaskPagination)
	resp.PageSize = pageSize
	resp.TotalPage = totalPage
	resp.CurrentPage = page
	resp.TotalCount = totalCount

	// 没有数据则返回空数据
	if totalCount <= 0 {
		return resp, nil
	}
	// 当前页数没有数据也返回空数据
	if totalCount < ((page - 1) * pageSize) {
		return resp, nil
	}
	if keyword.KeywordKey != "" && keyword.KeywordValue != "" {
		db = db.Where(fmt.Sprintf("%s = ?", keyword.KeywordKey), keyword.KeywordValue)
	}
	offset := int((page - 1) * pageSize)
	if err := db.Offset(offset).Limit(int(pageSize)).Find(&resp.Data).Error; err != nil {
		return nil, err
	}

	return resp, nil
}

func (m UmsMemberTaskPagination) Pagination() UmsMemberTaskPaginationBasic {
	return UmsMemberTaskPaginationBasic{
		CurrentPage: m.CurrentPage,
		PageSize:    m.PageSize,
		TotalPage:   m.TotalPage,
		TotalCount:  m.TotalCount,
	}
}

func (m UmsMemberTaskPagination) ToProto(to any, toData any, toPagination any) error {
	if to != nil {
		if err := copier.CopyWithOption(to, m, copier.Option{}); err != nil {
			return err
		}
	}
	if toData != nil {
		if err := copier.Copy(toData, m.Data); err != nil {
			return err
		}
	}
	if toPagination != nil {
		if err := copier.Copy(toPagination, m.Pagination()); err != nil {
			return err
		}
	}
	return nil
}

func (m *defaultUmsMemberTaskModel) Insert(ctx context.Context, data *UmsMemberTask) error {
	return m.OrmSession(ctx).Create(data).Error
}

func (m *defaultUmsMemberTaskModel) Update(ctx context.Context, data *UmsMemberTask) error {
	if data.Id <= 0 {
		return gorm.ErrMissingWhereClause
	}
	return m.OrmSession(ctx).Where("id = ?", data.Id).Save(data).Error
}
