// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"math"

	"fmt"
	"github.com/jinzhu/copier"
	"gorm.io/gorm"
)

var (
	_ sql.IsolationLevel
)

type (
	umsMemberStatisticsInfoModel interface {
		Insert(ctx context.Context, data *UmsMemberStatisticsInfo) error
		FindOne(ctx context.Context, id int64, preloadList ...string) (*UmsMemberStatisticsInfo, error)
		OrmSession(ctx context.Context) *gorm.DB
		Transaction(ctx context.Context, fc func(tx *gorm.DB) error, opts ...*sql.TxOptions) error
		FindPageListByBuilder(ctx context.Context, keyword *KeywordUmsMemberStatisticsInfoModel) (*UmsMemberStatisticsInfoPagination, error)
		Update(ctx context.Context, data *UmsMemberStatisticsInfo) error
		Delete(ctx context.Context, id int64) error
	}

	defaultUmsMemberStatisticsInfoModel struct {
		table   string
		ormConn *gorm.DB
	}

	UmsMemberStatisticsInfo struct {
		Id                  int64           `json:"id" gorm:"primary_key"`
		MemberId            sql.NullInt64   `json:"member_id"`
		ConsumeAmount       sql.NullFloat64 `json:"consume_amount"`     // 累计消费金额
		OrderCount          sql.NullInt64   `json:"order_count"`        // 订单数量
		CouponCount         sql.NullInt64   `json:"coupon_count"`       // 优惠券数量
		CommentCount        sql.NullInt64   `json:"comment_count"`      // 评价数
		ReturnOrderCount    sql.NullInt64   `json:"return_order_count"` // 退货数量
		LoginCount          sql.NullInt64   `json:"login_count"`        // 登录次数
		AttendCount         sql.NullInt64   `json:"attend_count"`       // 关注数量
		FansCount           sql.NullInt64   `json:"fans_count"`         // 粉丝数量
		CollectProductCount sql.NullInt64   `json:"collect_product_count"`
		CollectSubjectCount sql.NullInt64   `json:"collect_subject_count"`
		CollectTopicCount   sql.NullInt64   `json:"collect_topic_count"`
		CollectCommentCount sql.NullInt64   `json:"collect_comment_count"`
		InviteFriendCount   sql.NullInt64   `json:"invite_friend_count"`
		RecentOrderTime     sql.NullTime    `json:"recent_order_time"` // 最后一次下订单时间
		UmsMemberStatisticsInfoRelation
	}

	UmsMemberStatisticsInfoPagination struct {
		Data []*UmsMemberStatisticsInfo
		UmsMemberStatisticsInfoPaginationBasic
	}

	UmsMemberStatisticsInfoPaginationBasic struct {
		CurrentPage int64
		PageSize    int64
		TotalCount  int64
		TotalPage   int64
	}

	KeywordUmsMemberStatisticsInfoModel struct {
		KeywordKey     string //like 关键字
		KeywordValue   string //like 值
		Page, PageSize int64
	}
)

func newUmsMemberStatisticsInfoModel(db *gorm.DB) *defaultUmsMemberStatisticsInfoModel {
	return &defaultUmsMemberStatisticsInfoModel{
		table:   "`ums_member_statistics_info`",
		ormConn: db,
	}
}

func (UmsMemberStatisticsInfo) TableName() string {
	return "`ums_member_statistics_info`"
}

func (m UmsMemberStatisticsInfo) ToProto(toValue interface{}) error {
	return copier.Copy(toValue, &m)
}

func (m *defaultUmsMemberStatisticsInfoModel) Delete(ctx context.Context, id int64) error {
	return m.OrmSession(ctx).Delete(&UmsMemberStatisticsInfo{}, id).Error
}

func (m *defaultUmsMemberStatisticsInfoModel) FindOne(ctx context.Context, id int64, preloadList ...string) (*UmsMemberStatisticsInfo, error) {
	var mm UmsMemberStatisticsInfo
	db := m.OrmSession(ctx)
	for _, preload := range preloadList {
		db = db.Preload(preload)
	}
	err := db.First(&mm, id).Error
	switch err {
	case nil:
		return &mm, nil
	case gorm.ErrRecordNotFound:
		return nil, gorm.ErrRecordNotFound
	default:
		return nil, err
	}
}

func (m *defaultUmsMemberStatisticsInfoModel) OrmSession(ctx context.Context) *gorm.DB {
	return m.ormConn.Model(&UmsMemberStatisticsInfo{}).WithContext(ctx)
}

func (m *defaultUmsMemberStatisticsInfoModel) Transaction(ctx context.Context, fc func(tx *gorm.DB) error, opts ...*sql.TxOptions) error {
	return m.ormConn.WithContext(ctx).Transaction(fc, opts...)
}

func (m *defaultUmsMemberStatisticsInfoModel) FindPageListByBuilder(ctx context.Context, keyword *KeywordUmsMemberStatisticsInfoModel) (*UmsMemberStatisticsInfoPagination, error) {
	page := keyword.Page
	pageSize := keyword.PageSize
	// 总行数
	var totalCount int64
	db := m.OrmSession(ctx)
	if err := db.Count(&totalCount).Error; err != nil {
		return nil, err
	}
	// 总页数
	totalPage := int64(math.Ceil(float64(totalCount) / float64(pageSize)))

	resp := new(UmsMemberStatisticsInfoPagination)
	resp.PageSize = pageSize
	resp.TotalPage = totalPage
	resp.CurrentPage = page
	resp.TotalCount = totalCount

	// 没有数据则返回空数据
	if totalCount <= 0 {
		return resp, nil
	}
	// 当前页数没有数据也返回空数据
	if totalCount < ((page - 1) * pageSize) {
		return resp, nil
	}
	if keyword.KeywordKey != "" && keyword.KeywordValue != "" {
		db = db.Where(fmt.Sprintf("%s = ?", keyword.KeywordKey), keyword.KeywordValue)
	}
	offset := int((page - 1) * pageSize)
	if err := db.Offset(offset).Limit(int(pageSize)).Find(&resp.Data).Error; err != nil {
		return nil, err
	}

	return resp, nil
}

func (m UmsMemberStatisticsInfoPagination) Pagination() UmsMemberStatisticsInfoPaginationBasic {
	return UmsMemberStatisticsInfoPaginationBasic{
		CurrentPage: m.CurrentPage,
		PageSize:    m.PageSize,
		TotalPage:   m.TotalPage,
		TotalCount:  m.TotalCount,
	}
}

func (m UmsMemberStatisticsInfoPagination) ToProto(to any, toData any, toPagination any) error {
	if to != nil {
		if err := copier.CopyWithOption(to, m, copier.Option{}); err != nil {
			return err
		}
	}
	if toData != nil {
		if err := copier.Copy(toData, m.Data); err != nil {
			return err
		}
	}
	if toPagination != nil {
		if err := copier.Copy(toPagination, m.Pagination()); err != nil {
			return err
		}
	}
	return nil
}

func (m *defaultUmsMemberStatisticsInfoModel) Insert(ctx context.Context, data *UmsMemberStatisticsInfo) error {
	return m.OrmSession(ctx).Create(data).Error
}

func (m *defaultUmsMemberStatisticsInfoModel) Update(ctx context.Context, data *UmsMemberStatisticsInfo) error {
	if data.Id <= 0 {
		return gorm.ErrMissingWhereClause
	}
	return m.OrmSession(ctx).Where("id = ?", data.Id).Save(data).Error
}
