// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"math"

	"fmt"
	"github.com/jinzhu/copier"
	"gorm.io/gorm"
)

var (
	_ sql.IsolationLevel
)

type (
	umsAdminPermissionRelationModel interface {
		Insert(ctx context.Context, data *UmsAdminPermissionRelation) error
		FindOne(ctx context.Context, id int64, preloadList ...string) (*UmsAdminPermissionRelation, error)
		OrmSession(ctx context.Context) *gorm.DB
		Transaction(ctx context.Context, fc func(tx *gorm.DB) error, opts ...*sql.TxOptions) error
		FindPageListByBuilder(ormSession *gorm.DB, keyword *KeywordUmsAdminPermissionRelationModel) (*UmsAdminPermissionRelationPagination, error)
		Update(ctx context.Context, data *UmsAdminPermissionRelation) error
		Delete(ctx context.Context, id int64) error
	}

	defaultUmsAdminPermissionRelationModel struct {
		table   string
		ormConn *gorm.DB
	}

	UmsAdminPermissionRelation struct {
		Id           int64         `json:"id" gorm:"primary_key"`
		AdminId      sql.NullInt64 `json:"admin_id"`
		PermissionId sql.NullInt64 `json:"permission_id"`
		Type         sql.NullInt64 `json:"type"`
		UmsAdminPermissionRelationRelation
	}

	UmsAdminPermissionRelationPagination struct {
		Data []*UmsAdminPermissionRelation
		UmsAdminPermissionRelationPaginationBasic
	}

	UmsAdminPermissionRelationPaginationBasic struct {
		CurrentPage int64
		PageSize    int64
		TotalCount  int64
		TotalPage   int64
	}

	KeywordUmsAdminPermissionRelationModel struct {
		KeywordKey     string //like 关键字
		KeywordValue   string //like 值
		Page, PageSize int64
	}
)

func newUmsAdminPermissionRelationModel(db *gorm.DB) *defaultUmsAdminPermissionRelationModel {
	return &defaultUmsAdminPermissionRelationModel{
		table:   "`ums_admin_permission_relation`",
		ormConn: db,
	}
}

func (UmsAdminPermissionRelation) TableName() string {
	return "`ums_admin_permission_relation`"
}

func (m UmsAdminPermissionRelation) ToProto(toValue interface{}) error {
	return copier.Copy(toValue, &m)
}

func (m *defaultUmsAdminPermissionRelationModel) Delete(ctx context.Context, id int64) error {
	return m.OrmSession(ctx).Delete(&UmsAdminPermissionRelation{}, id).Error
}

func (m *defaultUmsAdminPermissionRelationModel) FindOne(ctx context.Context, id int64, preloadList ...string) (*UmsAdminPermissionRelation, error) {
	var mm UmsAdminPermissionRelation
	db := m.OrmSession(ctx)
	for _, preload := range preloadList {
		db = db.Preload(preload)
	}
	err := db.First(&mm, id).Error
	switch err {
	case nil:
		return &mm, nil
	case gorm.ErrRecordNotFound:
		return nil, gorm.ErrRecordNotFound
	default:
		return nil, err
	}
}

func (m *defaultUmsAdminPermissionRelationModel) OrmSession(ctx context.Context) *gorm.DB {
	return m.ormConn.Model(&UmsAdminPermissionRelation{}).WithContext(ctx)
}

func (m *defaultUmsAdminPermissionRelationModel) Transaction(ctx context.Context, fc func(tx *gorm.DB) error, opts ...*sql.TxOptions) error {
	return m.ormConn.WithContext(ctx).Transaction(fc, opts...)
}

func (m *defaultUmsAdminPermissionRelationModel) FindPageListByBuilder(db *gorm.DB, keyword *KeywordUmsAdminPermissionRelationModel) (*UmsAdminPermissionRelationPagination, error) {
	page := keyword.Page
	pageSize := keyword.PageSize
	// 总行数
	var totalCount int64
	if err := db.Count(&totalCount).Error; err != nil {
		return nil, err
	}
	// 总页数
	totalPage := int64(math.Ceil(float64(totalCount) / float64(pageSize)))

	resp := new(UmsAdminPermissionRelationPagination)
	resp.PageSize = pageSize
	resp.TotalPage = totalPage
	resp.CurrentPage = page
	resp.TotalCount = totalCount

	// 没有数据则返回空数据
	if totalCount <= 0 {
		return resp, nil
	}
	// 当前页数没有数据也返回空数据
	if totalCount < ((page - 1) * pageSize) {
		return resp, nil
	}
	if keyword.KeywordKey != "" && keyword.KeywordValue != "" {
		db = db.Where(fmt.Sprintf("%s = ?", keyword.KeywordKey), keyword.KeywordValue)
	}
	offset := int((page - 1) * pageSize)
	if err := db.Offset(offset).Limit(int(pageSize)).Find(&resp.Data).Error; err != nil {
		return nil, err
	}

	return resp, nil
}

func (m UmsAdminPermissionRelationPagination) Pagination() UmsAdminPermissionRelationPaginationBasic {
	return UmsAdminPermissionRelationPaginationBasic{
		CurrentPage: m.CurrentPage,
		PageSize:    m.PageSize,
		TotalPage:   m.TotalPage,
		TotalCount:  m.TotalCount,
	}
}

func (m UmsAdminPermissionRelationPagination) ToProto(to any, toData any, toPagination any) error {
	if to != nil {
		if err := copier.CopyWithOption(to, m, copier.Option{}); err != nil {
			return err
		}
	}
	if toData != nil {
		if err := copier.Copy(toData, m.Data); err != nil {
			return err
		}
	}
	if toPagination != nil {
		if err := copier.Copy(toPagination, m.Pagination()); err != nil {
			return err
		}
	}
	return nil
}

func (m *defaultUmsAdminPermissionRelationModel) Insert(ctx context.Context, data *UmsAdminPermissionRelation) error {
	return m.OrmSession(ctx).Create(data).Error
}

func (m *defaultUmsAdminPermissionRelationModel) Update(ctx context.Context, data *UmsAdminPermissionRelation) error {
	if data.Id <= 0 {
		return gorm.ErrMissingWhereClause
	}
	return m.OrmSession(ctx).Where("id = ?", data.Id).Save(data).Error
}
