// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"math"

	"github.com/jinzhu/copier"
	"gorm.io/gorm"
)

var (
	_ sql.IsolationLevel
)

type (
	umsAdminModel interface {
		Insert(ctx context.Context, data *UmsAdmin) error
		FindOne(ctx context.Context, id int64, preloadList ...string) (*UmsAdmin, error)
		OrmSession(ctx context.Context) *gorm.DB
		Transaction(ctx context.Context, fc func(tx *gorm.DB) error, opts ...*sql.TxOptions) error
		FindPageListByBuilder(ormSession *gorm.DB, page, pageSize int64) (*UmsAdminPagination, error)
		Update(ctx context.Context, data *UmsAdmin) error
		Delete(ctx context.Context, id int64) error
	}

	defaultUmsAdminModel struct {
		table   string
		ormConn *gorm.DB
	}

	UmsAdmin struct {
		Id         int64          `json:"id" gorm:"primary_key"`
		Username   sql.NullString `json:"username"`
		Password   sql.NullString `json:"password"`
		Icon       sql.NullString `json:"icon"`        // 头像
		Email      sql.NullString `json:"email"`       // 邮箱
		NickName   sql.NullString `json:"nick_name"`   // 昵称
		Note       sql.NullString `json:"note"`        // 备注信息
		CreateTime sql.NullTime   `json:"create_time"` // 创建时间
		LoginTime  sql.NullTime   `json:"login_time"`  // 最后登录时间
		Status     int64          `json:"status"`      // 帐号启用状态：0->禁用；1->启用
		UmsAdminRelation
	}

	UmsAdminPagination struct {
		Data []*UmsAdmin
		UmsAdminPaginationBasic
	}

	UmsAdminPaginationBasic struct {
		CurrentPage int64
		PageSize    int64
		TotalCount  int64
		TotalPage   int64
	}
)

func newUmsAdminModel(db *gorm.DB) *defaultUmsAdminModel {
	return &defaultUmsAdminModel{
		table:   "`ums_admin`",
		ormConn: db,
	}
}

func (UmsAdmin) TableName() string {
	return "`ums_admin`"
}

func (m UmsAdmin) ToProto(toValue interface{}) error {
	return copier.Copy(toValue, &m)
}

func (m *defaultUmsAdminModel) Delete(ctx context.Context, id int64) error {
	return m.OrmSession(ctx).Delete(&UmsAdmin{}, id).Error
}

func (m *defaultUmsAdminModel) FindOne(ctx context.Context, id int64, preloadList ...string) (*UmsAdmin, error) {
	var mm UmsAdmin
	db := m.OrmSession(ctx)
	for _, preload := range preloadList {
		db = db.Preload(preload)
	}
	err := db.First(&mm, id).Error
	switch err {
	case nil:
		return &mm, nil
	case gorm.ErrRecordNotFound:
		return nil, gorm.ErrRecordNotFound
	default:
		return nil, err
	}
}

func (m *defaultUmsAdminModel) OrmSession(ctx context.Context) *gorm.DB {
	return m.ormConn.Model(&UmsAdmin{}).WithContext(ctx)
}

func (m *defaultUmsAdminModel) Transaction(ctx context.Context, fc func(tx *gorm.DB) error, opts ...*sql.TxOptions) error {
	return m.ormConn.WithContext(ctx).Transaction(fc, opts...)
}

func (m *defaultUmsAdminModel) FindPageListByBuilder(db *gorm.DB, page, pageSize int64) (*UmsAdminPagination, error) {
	// 总行数
	var totalCount int64
	if err := db.Count(&totalCount).Error; err != nil {
		return nil, err
	}
	// 总页数
	totalPage := int64(math.Ceil(float64(totalCount) / float64(pageSize)))

	resp := new(UmsAdminPagination)
	resp.PageSize = pageSize
	resp.TotalPage = totalPage
	resp.CurrentPage = page
	resp.TotalCount = totalCount

	// 没有数据则返回空数据
	if totalCount <= 0 {
		return resp, nil
	}
	// 当前页数没有数据也返回空数据
	if totalCount < ((page - 1) * pageSize) {
		return resp, nil
	}

	offset := int((page - 1) * pageSize)
	if err := db.Offset(offset).Limit(int(pageSize)).Find(&resp.Data).Error; err != nil {
		return nil, err
	}

	return resp, nil
}

func (m UmsAdminPagination) Pagination() UmsAdminPaginationBasic {
	return UmsAdminPaginationBasic{
		CurrentPage: m.CurrentPage,
		PageSize:    m.PageSize,
		TotalPage:   m.TotalPage,
		TotalCount:  m.TotalCount,
	}
}

func (m UmsAdminPagination) ToProto(to any, toData any, toPagination any) error {
	if to != nil {
		if err := copier.CopyWithOption(to, m, copier.Option{}); err != nil {
			return err
		}
	}
	if toData != nil {
		if err := copier.Copy(toData, m.Data); err != nil {
			return err
		}
	}
	if toPagination != nil {
		if err := copier.Copy(toPagination, m.Pagination()); err != nil {
			return err
		}
	}
	return nil
}

func (m *defaultUmsAdminModel) Insert(ctx context.Context, data *UmsAdmin) error {
	return m.OrmSession(ctx).Create(data).Error
}

func (m *defaultUmsAdminModel) Update(ctx context.Context, data *UmsAdmin) error {
	if data.Id <= 0 {
		return gorm.ErrMissingWhereClause
	}
	return m.OrmSession(ctx).Where("id = ?", data.Id).Save(data).Error
}
