// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"math"

	"fmt"
	"github.com/jinzhu/copier"
	"gorm.io/gorm"
)

var (
	_ sql.IsolationLevel
)

type (
	umsResourceCategoryModel interface {
		Insert(ctx context.Context, data *UmsResourceCategory) error
		FindOne(ctx context.Context, id int64, preloadList ...string) (*UmsResourceCategory, error)
		OrmSession(ctx context.Context) *gorm.DB
		Transaction(ctx context.Context, fc func(tx *gorm.DB) error, opts ...*sql.TxOptions) error
		FindPageListByBuilder(ormSession *gorm.DB, keyword *KeywordUmsResourceCategoryModel) (*UmsResourceCategoryPagination, error)
		Update(ctx context.Context, data *UmsResourceCategory) error
		Delete(ctx context.Context, id int64) error
	}

	defaultUmsResourceCategoryModel struct {
		table   string
		ormConn *gorm.DB
	}

	UmsResourceCategory struct {
		Id         int64          `json:"id" gorm:"primary_key"`
		CreateTime sql.NullTime   `json:"create_time"` // 创建时间
		Name       sql.NullString `json:"name"`        // 分类名称
		Sort       sql.NullInt64  `json:"sort"`        // 排序
		UmsResourceCategoryRelation
	}

	UmsResourceCategoryPagination struct {
		Data []*UmsResourceCategory
		UmsResourceCategoryPaginationBasic
	}

	UmsResourceCategoryPaginationBasic struct {
		CurrentPage int64
		PageSize    int64
		TotalCount  int64
		TotalPage   int64
	}

	KeywordUmsResourceCategoryModel struct {
		KeywordKey     string //like 关键字
		KeywordValue   string //like 值
		Page, PageSize int64
	}
)

func newUmsResourceCategoryModel(db *gorm.DB) *defaultUmsResourceCategoryModel {
	return &defaultUmsResourceCategoryModel{
		table:   "`ums_resource_category`",
		ormConn: db,
	}
}

func (UmsResourceCategory) TableName() string {
	return "`ums_resource_category`"
}

func (m UmsResourceCategory) ToProto(toValue interface{}) error {
	return copier.Copy(toValue, &m)
}

func (m *defaultUmsResourceCategoryModel) Delete(ctx context.Context, id int64) error {
	return m.OrmSession(ctx).Delete(&UmsResourceCategory{}, id).Error
}

func (m *defaultUmsResourceCategoryModel) FindOne(ctx context.Context, id int64, preloadList ...string) (*UmsResourceCategory, error) {
	var mm UmsResourceCategory
	db := m.OrmSession(ctx)
	for _, preload := range preloadList {
		db = db.Preload(preload)
	}
	err := db.First(&mm, id).Error
	switch err {
	case nil:
		return &mm, nil
	case gorm.ErrRecordNotFound:
		return nil, gorm.ErrRecordNotFound
	default:
		return nil, err
	}
}

func (m *defaultUmsResourceCategoryModel) OrmSession(ctx context.Context) *gorm.DB {
	return m.ormConn.Model(&UmsResourceCategory{}).WithContext(ctx)
}

func (m *defaultUmsResourceCategoryModel) Transaction(ctx context.Context, fc func(tx *gorm.DB) error, opts ...*sql.TxOptions) error {
	return m.ormConn.WithContext(ctx).Transaction(fc, opts...)
}

func (m *defaultUmsResourceCategoryModel) FindPageListByBuilder(db *gorm.DB, keyword *KeywordUmsResourceCategoryModel) (*UmsResourceCategoryPagination, error) {
	page := keyword.Page
	pageSize := keyword.PageSize
	// 总行数
	var totalCount int64
	if err := db.Count(&totalCount).Error; err != nil {
		return nil, err
	}
	// 总页数
	totalPage := int64(math.Ceil(float64(totalCount) / float64(pageSize)))

	resp := new(UmsResourceCategoryPagination)
	resp.PageSize = pageSize
	resp.TotalPage = totalPage
	resp.CurrentPage = page
	resp.TotalCount = totalCount

	// 没有数据则返回空数据
	if totalCount <= 0 {
		return resp, nil
	}
	// 当前页数没有数据也返回空数据
	if totalCount < ((page - 1) * pageSize) {
		return resp, nil
	}
	if keyword.KeywordKey != "" && keyword.KeywordValue != "" {
		db = db.Where(fmt.Sprintf("%s = ?", keyword.KeywordKey), keyword.KeywordValue)
	}
	offset := int((page - 1) * pageSize)
	if err := db.Offset(offset).Limit(int(pageSize)).Find(&resp.Data).Error; err != nil {
		return nil, err
	}

	return resp, nil
}

func (m UmsResourceCategoryPagination) Pagination() UmsResourceCategoryPaginationBasic {
	return UmsResourceCategoryPaginationBasic{
		CurrentPage: m.CurrentPage,
		PageSize:    m.PageSize,
		TotalPage:   m.TotalPage,
		TotalCount:  m.TotalCount,
	}
}

func (m UmsResourceCategoryPagination) ToProto(to any, toData any, toPagination any) error {
	if to != nil {
		if err := copier.CopyWithOption(to, m, copier.Option{}); err != nil {
			return err
		}
	}
	if toData != nil {
		if err := copier.Copy(toData, m.Data); err != nil {
			return err
		}
	}
	if toPagination != nil {
		if err := copier.Copy(toPagination, m.Pagination()); err != nil {
			return err
		}
	}
	return nil
}

func (m *defaultUmsResourceCategoryModel) Insert(ctx context.Context, data *UmsResourceCategory) error {
	return m.OrmSession(ctx).Create(data).Error
}

func (m *defaultUmsResourceCategoryModel) Update(ctx context.Context, data *UmsResourceCategory) error {
	if data.Id <= 0 {
		return gorm.ErrMissingWhereClause
	}
	return m.OrmSession(ctx).Where("id = ?", data.Id).Save(data).Error
}
