// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"math"

	"fmt"
	"github.com/jinzhu/copier"
	"gorm.io/gorm"
)

var (
	_ sql.IsolationLevel
)

type (
	umsMenuModel interface {
		Insert(ctx context.Context, data *UmsMenu) error
		FindOne(ctx context.Context, id int64, preloadList ...string) (*UmsMenu, error)
		OrmSession(ctx context.Context) *gorm.DB
		Transaction(ctx context.Context, fc func(tx *gorm.DB) error, opts ...*sql.TxOptions) error
		FindPageListByBuilder(ctx context.Context, keyword *KeywordUmsMenuModel) (*UmsMenuPagination, error)
		Update(ctx context.Context, data *UmsMenu) error
		Delete(ctx context.Context, id int64) error
	}

	defaultUmsMenuModel struct {
		table   string
		ormConn *gorm.DB
	}

	UmsMenu struct {
		Id         int64          `json:"id" gorm:"primary_key"`
		ParentId   sql.NullInt64  `json:"parent_id"`   // 父级ID
		CreateTime sql.NullTime   `json:"create_time"` // 创建时间
		Title      sql.NullString `json:"title"`       // 菜单名称
		Level      sql.NullInt64  `json:"level"`       // 菜单级数
		Sort       sql.NullInt64  `json:"sort"`        // 菜单排序
		Name       sql.NullString `json:"name"`        // 前端名称
		Icon       sql.NullString `json:"icon"`        // 前端图标
		Hidden     sql.NullInt64  `json:"hidden"`      // 前端隐藏
		UmsMenuRelation
	}

	UmsMenuPagination struct {
		Data []*UmsMenu
		UmsMenuPaginationBasic
	}

	UmsMenuPaginationBasic struct {
		CurrentPage int64
		PageSize    int64
		TotalCount  int64
		TotalPage   int64
	}

	KeywordUmsMenuModel struct {
		KeywordKey     string //like 关键字
		KeywordValue   string //like 值
		Page, PageSize int64
	}
)

func newUmsMenuModel(db *gorm.DB) *defaultUmsMenuModel {
	return &defaultUmsMenuModel{
		table:   "`ums_menu`",
		ormConn: db,
	}
}

func (UmsMenu) TableName() string {
	return "`ums_menu`"
}

func (m UmsMenu) ToProto(toValue interface{}) error {
	return copier.Copy(toValue, &m)
}

func (m *defaultUmsMenuModel) Delete(ctx context.Context, id int64) error {
	return m.OrmSession(ctx).Delete(&UmsMenu{}, id).Error
}

func (m *defaultUmsMenuModel) FindOne(ctx context.Context, id int64, preloadList ...string) (*UmsMenu, error) {
	var mm UmsMenu
	db := m.OrmSession(ctx)
	for _, preload := range preloadList {
		db = db.Preload(preload)
	}
	err := db.First(&mm, id).Error
	switch err {
	case nil:
		return &mm, nil
	case gorm.ErrRecordNotFound:
		return nil, gorm.ErrRecordNotFound
	default:
		return nil, err
	}
}

func (m *defaultUmsMenuModel) OrmSession(ctx context.Context) *gorm.DB {
	return m.ormConn.Model(&UmsMenu{}).WithContext(ctx)
}

func (m *defaultUmsMenuModel) Transaction(ctx context.Context, fc func(tx *gorm.DB) error, opts ...*sql.TxOptions) error {
	return m.ormConn.WithContext(ctx).Transaction(fc, opts...)
}

func (m *defaultUmsMenuModel) FindPageListByBuilder(ctx context.Context, keyword *KeywordUmsMenuModel) (*UmsMenuPagination, error) {
	page := keyword.Page
	pageSize := keyword.PageSize
	// 总行数
	var totalCount int64
	db := m.OrmSession(ctx)
	if err := db.Count(&totalCount).Error; err != nil {
		return nil, err
	}
	// 总页数
	totalPage := int64(math.Ceil(float64(totalCount) / float64(pageSize)))

	resp := new(UmsMenuPagination)
	resp.PageSize = pageSize
	resp.TotalPage = totalPage
	resp.CurrentPage = page
	resp.TotalCount = totalCount

	// 没有数据则返回空数据
	if totalCount <= 0 {
		return resp, nil
	}
	// 当前页数没有数据也返回空数据
	if totalCount < ((page - 1) * pageSize) {
		return resp, nil
	}
	if keyword.KeywordKey != "" && keyword.KeywordValue != "" {
		db = db.Where(fmt.Sprintf("%s = ?", keyword.KeywordKey), keyword.KeywordValue)
	}
	offset := int((page - 1) * pageSize)
	if err := db.Offset(offset).Limit(int(pageSize)).Find(&resp.Data).Error; err != nil {
		return nil, err
	}

	return resp, nil
}

func (m UmsMenuPagination) Pagination() UmsMenuPaginationBasic {
	return UmsMenuPaginationBasic{
		CurrentPage: m.CurrentPage,
		PageSize:    m.PageSize,
		TotalPage:   m.TotalPage,
		TotalCount:  m.TotalCount,
	}
}

func (m UmsMenuPagination) ToProto(to any, toData any, toPagination any) error {
	if to != nil {
		if err := copier.CopyWithOption(to, m, copier.Option{}); err != nil {
			return err
		}
	}
	if toData != nil {
		if err := copier.Copy(toData, m.Data); err != nil {
			return err
		}
	}
	if toPagination != nil {
		if err := copier.Copy(toPagination, m.Pagination()); err != nil {
			return err
		}
	}
	return nil
}

func (m *defaultUmsMenuModel) Insert(ctx context.Context, data *UmsMenu) error {
	return m.OrmSession(ctx).Create(data).Error
}

func (m *defaultUmsMenuModel) Update(ctx context.Context, data *UmsMenu) error {
	if data.Id <= 0 {
		return gorm.ErrMissingWhereClause
	}
	return m.OrmSession(ctx).Where("id = ?", data.Id).Save(data).Error
}
