// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"math"

	"fmt"
	"github.com/jinzhu/copier"
	"gorm.io/gorm"
)

var (
	_ sql.IsolationLevel
)

type (
	umsPermissionModel interface {
		Insert(ctx context.Context, data *UmsPermission) error
		FindOne(ctx context.Context, id int64, preloadList ...string) (*UmsPermission, error)
		OrmSession(ctx context.Context) *gorm.DB
		Transaction(ctx context.Context, fc func(tx *gorm.DB) error, opts ...*sql.TxOptions) error
		FindPageListByBuilder(ctx context.Context, keyword *KeywordUmsPermissionModel) (*UmsPermissionPagination, error)
		Update(ctx context.Context, data *UmsPermission) error
		Delete(ctx context.Context, id int64) error
	}

	defaultUmsPermissionModel struct {
		table   string
		ormConn *gorm.DB
	}

	UmsPermission struct {
		Id         int64          `json:"id" gorm:"primary_key"`
		Pid        sql.NullInt64  `json:"pid"`         // 父级权限id
		Name       sql.NullString `json:"name"`        // 名称
		Value      sql.NullString `json:"value"`       // 权限值
		Icon       sql.NullString `json:"icon"`        // 图标
		Type       sql.NullInt64  `json:"type"`        // 权限类型：0->目录；1->菜单；2->按钮（接口绑定权限）
		Uri        sql.NullString `json:"uri"`         // 前端资源路径
		Status     sql.NullInt64  `json:"status"`      // 启用状态；0->禁用；1->启用
		CreateTime sql.NullTime   `json:"create_time"` // 创建时间
		Sort       sql.NullInt64  `json:"sort"`        // 排序
		UmsPermissionRelation
	}

	UmsPermissionPagination struct {
		Data []*UmsPermission
		UmsPermissionPaginationBasic
	}

	UmsPermissionPaginationBasic struct {
		CurrentPage int64
		PageSize    int64
		TotalCount  int64
		TotalPage   int64
	}

	KeywordUmsPermissionModel struct {
		KeywordKey     string //like 关键字
		KeywordValue   string //like 值
		Page, PageSize int64
	}
)

func newUmsPermissionModel(db *gorm.DB) *defaultUmsPermissionModel {
	return &defaultUmsPermissionModel{
		table:   "`ums_permission`",
		ormConn: db,
	}
}

func (UmsPermission) TableName() string {
	return "`ums_permission`"
}

func (m UmsPermission) ToProto(toValue interface{}) error {
	return copier.Copy(toValue, &m)
}

func (m *defaultUmsPermissionModel) Delete(ctx context.Context, id int64) error {
	return m.OrmSession(ctx).Delete(&UmsPermission{}, id).Error
}

func (m *defaultUmsPermissionModel) FindOne(ctx context.Context, id int64, preloadList ...string) (*UmsPermission, error) {
	var mm UmsPermission
	db := m.OrmSession(ctx)
	for _, preload := range preloadList {
		db = db.Preload(preload)
	}
	err := db.First(&mm, id).Error
	switch err {
	case nil:
		return &mm, nil
	case gorm.ErrRecordNotFound:
		return nil, gorm.ErrRecordNotFound
	default:
		return nil, err
	}
}

func (m *defaultUmsPermissionModel) OrmSession(ctx context.Context) *gorm.DB {
	return m.ormConn.Model(&UmsPermission{}).WithContext(ctx)
}

func (m *defaultUmsPermissionModel) Transaction(ctx context.Context, fc func(tx *gorm.DB) error, opts ...*sql.TxOptions) error {
	return m.ormConn.WithContext(ctx).Transaction(fc, opts...)
}

func (m *defaultUmsPermissionModel) FindPageListByBuilder(ctx context.Context, keyword *KeywordUmsPermissionModel) (*UmsPermissionPagination, error) {
	page := keyword.Page
	pageSize := keyword.PageSize
	// 总行数
	var totalCount int64
	db := m.OrmSession(ctx)
	if err := db.Count(&totalCount).Error; err != nil {
		return nil, err
	}
	// 总页数
	totalPage := int64(math.Ceil(float64(totalCount) / float64(pageSize)))

	resp := new(UmsPermissionPagination)
	resp.PageSize = pageSize
	resp.TotalPage = totalPage
	resp.CurrentPage = page
	resp.TotalCount = totalCount

	// 没有数据则返回空数据
	if totalCount <= 0 {
		return resp, nil
	}
	// 当前页数没有数据也返回空数据
	if totalCount < ((page - 1) * pageSize) {
		return resp, nil
	}
	if keyword.KeywordKey != "" && keyword.KeywordValue != "" {
		db = db.Where(fmt.Sprintf("%s = ?", keyword.KeywordKey), keyword.KeywordValue)
	}
	offset := int((page - 1) * pageSize)
	if err := db.Offset(offset).Limit(int(pageSize)).Find(&resp.Data).Error; err != nil {
		return nil, err
	}

	return resp, nil
}

func (m UmsPermissionPagination) Pagination() UmsPermissionPaginationBasic {
	return UmsPermissionPaginationBasic{
		CurrentPage: m.CurrentPage,
		PageSize:    m.PageSize,
		TotalPage:   m.TotalPage,
		TotalCount:  m.TotalCount,
	}
}

func (m UmsPermissionPagination) ToProto(to any, toData any, toPagination any) error {
	if to != nil {
		if err := copier.CopyWithOption(to, m, copier.Option{}); err != nil {
			return err
		}
	}
	if toData != nil {
		if err := copier.Copy(toData, m.Data); err != nil {
			return err
		}
	}
	if toPagination != nil {
		if err := copier.Copy(toPagination, m.Pagination()); err != nil {
			return err
		}
	}
	return nil
}

func (m *defaultUmsPermissionModel) Insert(ctx context.Context, data *UmsPermission) error {
	return m.OrmSession(ctx).Create(data).Error
}

func (m *defaultUmsPermissionModel) Update(ctx context.Context, data *UmsPermission) error {
	if data.Id <= 0 {
		return gorm.ErrMissingWhereClause
	}
	return m.OrmSession(ctx).Where("id = ?", data.Id).Save(data).Error
}
