// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"math"

	"github.com/jinzhu/copier"
	"gorm.io/gorm"
)

var (
	_ sql.IsolationLevel
)

type (
	umsAdminRoleRelationModel interface {
		Insert(ctx context.Context, data *UmsAdminRoleRelation) error
		FindOne(ctx context.Context, id int64, preloadList ...string) (*UmsAdminRoleRelation, error)
		OrmSession(ctx context.Context) *gorm.DB
		Transaction(ctx context.Context, fc func(tx *gorm.DB) error, opts ...*sql.TxOptions) error
		FindPageListByBuilder(ormSession *gorm.DB, page, pageSize int64) (*UmsAdminRoleRelationPagination, error)
		Update(ctx context.Context, data *UmsAdminRoleRelation) error
		Delete(ctx context.Context, id int64) error
	}

	defaultUmsAdminRoleRelationModel struct {
		table   string
		ormConn *gorm.DB
	}

	UmsAdminRoleRelation struct {
		Id      int64         `json:"id" gorm:"primary_key"`
		AdminId sql.NullInt64 `json:"admin_id"`
		RoleId  sql.NullInt64 `json:"role_id"`
		//UmsRoles []*UmsRole    `json:"umsRole" gorm:"foreignKey:Id;references:RoleId"`
		UmsAdminRoleRelationRelation
	}

	UmsAdminRoleRelationPagination struct {
		Data []*UmsAdminRoleRelation
		UmsAdminRoleRelationPaginationBasic
	}

	UmsAdminRoleRelationPaginationBasic struct {
		CurrentPage int64
		PageSize    int64
		TotalCount  int64
		TotalPage   int64
	}
)

func newUmsAdminRoleRelationModel(db *gorm.DB) *defaultUmsAdminRoleRelationModel {
	return &defaultUmsAdminRoleRelationModel{
		table:   "`ums_admin_role_relation`",
		ormConn: db,
	}
}

func (UmsAdminRoleRelation) TableName() string {
	return "`ums_admin_role_relation`"
}

func (m UmsAdminRoleRelation) ToProto(toValue interface{}) error {
	return copier.Copy(toValue, &m)
}

func (m *defaultUmsAdminRoleRelationModel) Delete(ctx context.Context, id int64) error {
	return m.OrmSession(ctx).Delete(&UmsAdminRoleRelation{}, id).Error
}

func (m *defaultUmsAdminRoleRelationModel) FindOne(ctx context.Context, id int64, preloadList ...string) (*UmsAdminRoleRelation, error) {
	var mm UmsAdminRoleRelation
	db := m.OrmSession(ctx)
	for _, preload := range preloadList {
		db = db.Preload(preload)
	}
	err := db.First(&mm, id).Error
	switch err {
	case nil:
		return &mm, nil
	case gorm.ErrRecordNotFound:
		return nil, gorm.ErrRecordNotFound
	default:
		return nil, err
	}
}

func (m *defaultUmsAdminRoleRelationModel) OrmSession(ctx context.Context) *gorm.DB {
	return m.ormConn.Model(&UmsAdminRoleRelation{}).WithContext(ctx)
}

func (m *defaultUmsAdminRoleRelationModel) Transaction(ctx context.Context, fc func(tx *gorm.DB) error, opts ...*sql.TxOptions) error {
	return m.ormConn.WithContext(ctx).Transaction(fc, opts...)
}

func (m *defaultUmsAdminRoleRelationModel) FindPageListByBuilder(db *gorm.DB, page, pageSize int64) (*UmsAdminRoleRelationPagination, error) {
	// 总行数
	var totalCount int64
	if err := db.Count(&totalCount).Error; err != nil {
		return nil, err
	}
	// 总页数
	totalPage := int64(math.Ceil(float64(totalCount) / float64(pageSize)))

	resp := new(UmsAdminRoleRelationPagination)
	resp.PageSize = pageSize
	resp.TotalPage = totalPage
	resp.CurrentPage = page
	resp.TotalCount = totalCount

	// 没有数据则返回空数据
	if totalCount <= 0 {
		return resp, nil
	}
	// 当前页数没有数据也返回空数据
	if totalCount < ((page - 1) * pageSize) {
		return resp, nil
	}

	offset := int((page - 1) * pageSize)
	if err := db.Offset(offset).Limit(int(pageSize)).Find(&resp.Data).Error; err != nil {
		return nil, err
	}

	return resp, nil
}

func (m UmsAdminRoleRelationPagination) Pagination() UmsAdminRoleRelationPaginationBasic {
	return UmsAdminRoleRelationPaginationBasic{
		CurrentPage: m.CurrentPage,
		PageSize:    m.PageSize,
		TotalPage:   m.TotalPage,
		TotalCount:  m.TotalCount,
	}
}

func (m UmsAdminRoleRelationPagination) ToProto(to any, toData any, toPagination any) error {
	if to != nil {
		if err := copier.CopyWithOption(to, m, copier.Option{}); err != nil {
			return err
		}
	}
	if toData != nil {
		if err := copier.Copy(toData, m.Data); err != nil {
			return err
		}
	}
	if toPagination != nil {
		if err := copier.Copy(toPagination, m.Pagination()); err != nil {
			return err
		}
	}
	return nil
}

func (m *defaultUmsAdminRoleRelationModel) Insert(ctx context.Context, data *UmsAdminRoleRelation) error {
	return m.OrmSession(ctx).Create(data).Error
}

func (m *defaultUmsAdminRoleRelationModel) Update(ctx context.Context, data *UmsAdminRoleRelation) error {
	if data.Id <= 0 {
		return gorm.ErrMissingWhereClause
	}
	return m.OrmSession(ctx).Where("id = ?", data.Id).Save(data).Error
}
