// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"math"

	"fmt"
	"github.com/jinzhu/copier"
	"gorm.io/gorm"
)

var (
	_ sql.IsolationLevel
)

type (
	umsMemberReceiveAddressModel interface {
		Insert(ctx context.Context, data *UmsMemberReceiveAddress) error
		FindOne(ctx context.Context, id int64, preloadList ...string) (*UmsMemberReceiveAddress, error)
		OrmSession(ctx context.Context) *gorm.DB
		Transaction(ctx context.Context, fc func(tx *gorm.DB) error, opts ...*sql.TxOptions) error
		FindPageListByBuilder(ormSession *gorm.DB, keyword *KeywordUmsMemberReceiveAddressModel) (*UmsMemberReceiveAddressPagination, error)
		Update(ctx context.Context, data *UmsMemberReceiveAddress) error
		Delete(ctx context.Context, id int64) error
	}

	defaultUmsMemberReceiveAddressModel struct {
		table   string
		ormConn *gorm.DB
	}

	UmsMemberReceiveAddress struct {
		Id            int64          `json:"id" gorm:"primary_key"`
		MemberId      sql.NullInt64  `json:"member_id"`
		Name          sql.NullString `json:"name"` // 收货人名称
		PhoneNumber   sql.NullString `json:"phone_number"`
		DefaultStatus sql.NullInt64  `json:"default_status"` // 是否为默认
		PostCode      sql.NullString `json:"post_code"`      // 邮政编码
		Province      sql.NullString `json:"province"`       // 省份/直辖市
		City          sql.NullString `json:"city"`           // 城市
		Region        sql.NullString `json:"region"`         // 区
		DetailAddress sql.NullString `json:"detail_address"` // 详细地址(街道)
		UmsMemberReceiveAddressRelation
	}

	UmsMemberReceiveAddressPagination struct {
		Data []*UmsMemberReceiveAddress
		UmsMemberReceiveAddressPaginationBasic
	}

	UmsMemberReceiveAddressPaginationBasic struct {
		CurrentPage int64
		PageSize    int64
		TotalCount  int64
		TotalPage   int64
	}

	KeywordUmsMemberReceiveAddressModel struct {
		KeywordKey     string //like 关键字
		KeywordValue   string //like 值
		Page, PageSize int64
	}
)

func newUmsMemberReceiveAddressModel(db *gorm.DB) *defaultUmsMemberReceiveAddressModel {
	return &defaultUmsMemberReceiveAddressModel{
		table:   "`ums_member_receive_address`",
		ormConn: db,
	}
}

func (UmsMemberReceiveAddress) TableName() string {
	return "`ums_member_receive_address`"
}

func (m UmsMemberReceiveAddress) ToProto(toValue interface{}) error {
	return copier.Copy(toValue, &m)
}

func (m *defaultUmsMemberReceiveAddressModel) Delete(ctx context.Context, id int64) error {
	return m.OrmSession(ctx).Delete(&UmsMemberReceiveAddress{}, id).Error
}

func (m *defaultUmsMemberReceiveAddressModel) FindOne(ctx context.Context, id int64, preloadList ...string) (*UmsMemberReceiveAddress, error) {
	var mm UmsMemberReceiveAddress
	db := m.OrmSession(ctx)
	for _, preload := range preloadList {
		db = db.Preload(preload)
	}
	err := db.First(&mm, id).Error
	switch err {
	case nil:
		return &mm, nil
	case gorm.ErrRecordNotFound:
		return nil, gorm.ErrRecordNotFound
	default:
		return nil, err
	}
}

func (m *defaultUmsMemberReceiveAddressModel) OrmSession(ctx context.Context) *gorm.DB {
	return m.ormConn.Model(&UmsMemberReceiveAddress{}).WithContext(ctx)
}

func (m *defaultUmsMemberReceiveAddressModel) Transaction(ctx context.Context, fc func(tx *gorm.DB) error, opts ...*sql.TxOptions) error {
	return m.ormConn.WithContext(ctx).Transaction(fc, opts...)
}

func (m *defaultUmsMemberReceiveAddressModel) FindPageListByBuilder(db *gorm.DB, keyword *KeywordUmsMemberReceiveAddressModel) (*UmsMemberReceiveAddressPagination, error) {
	page := keyword.Page
	pageSize := keyword.PageSize
	// 总行数
	var totalCount int64
	if err := db.Count(&totalCount).Error; err != nil {
		return nil, err
	}
	// 总页数
	totalPage := int64(math.Ceil(float64(totalCount) / float64(pageSize)))

	resp := new(UmsMemberReceiveAddressPagination)
	resp.PageSize = pageSize
	resp.TotalPage = totalPage
	resp.CurrentPage = page
	resp.TotalCount = totalCount

	// 没有数据则返回空数据
	if totalCount <= 0 {
		return resp, nil
	}
	// 当前页数没有数据也返回空数据
	if totalCount < ((page - 1) * pageSize) {
		return resp, nil
	}
	if keyword.KeywordKey != "" && keyword.KeywordValue != "" {
		db = db.Where(fmt.Sprintf("%s = ?", keyword.KeywordKey), keyword.KeywordValue)
	}
	offset := int((page - 1) * pageSize)
	if err := db.Offset(offset).Limit(int(pageSize)).Find(&resp.Data).Error; err != nil {
		return nil, err
	}

	return resp, nil
}

func (m UmsMemberReceiveAddressPagination) Pagination() UmsMemberReceiveAddressPaginationBasic {
	return UmsMemberReceiveAddressPaginationBasic{
		CurrentPage: m.CurrentPage,
		PageSize:    m.PageSize,
		TotalPage:   m.TotalPage,
		TotalCount:  m.TotalCount,
	}
}

func (m UmsMemberReceiveAddressPagination) ToProto(to any, toData any, toPagination any) error {
	if to != nil {
		if err := copier.CopyWithOption(to, m, copier.Option{}); err != nil {
			return err
		}
	}
	if toData != nil {
		if err := copier.Copy(toData, m.Data); err != nil {
			return err
		}
	}
	if toPagination != nil {
		if err := copier.Copy(toPagination, m.Pagination()); err != nil {
			return err
		}
	}
	return nil
}

func (m *defaultUmsMemberReceiveAddressModel) Insert(ctx context.Context, data *UmsMemberReceiveAddress) error {
	return m.OrmSession(ctx).Create(data).Error
}

func (m *defaultUmsMemberReceiveAddressModel) Update(ctx context.Context, data *UmsMemberReceiveAddress) error {
	if data.Id <= 0 {
		return gorm.ErrMissingWhereClause
	}
	return m.OrmSession(ctx).Where("id = ?", data.Id).Save(data).Error
}
