// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"math"

	"github.com/jinzhu/copier"
	"gorm.io/gorm"
)

var (
	_ sql.IsolationLevel
)

type (
	umsResourceModel interface {
		Insert(ctx context.Context, data *UmsResource) error
		FindOne(ctx context.Context, id int64, preloadList ...string) (*UmsResource, error)
		OrmSession(ctx context.Context) *gorm.DB
		Transaction(ctx context.Context, fc func(tx *gorm.DB) error, opts ...*sql.TxOptions) error
		FindPageListByBuilder(ormSession *gorm.DB, page, pageSize int64) (*UmsResourcePagination, error)
		Update(ctx context.Context, data *UmsResource) error
		Delete(ctx context.Context, id int64) error
	}

	defaultUmsResourceModel struct {
		table   string
		ormConn *gorm.DB
	}

	UmsResource struct {
		Id          int64          `json:"id" gorm:"primary_key"`
		CreateTime  sql.NullTime   `json:"create_time"` // 创建时间
		Name        sql.NullString `json:"name"`        // 资源名称
		Url         sql.NullString `json:"url"`         // 资源URL
		Description sql.NullString `json:"description"` // 描述
		CategoryId  sql.NullInt64  `json:"category_id"` // 资源分类ID
		UmsResourceRelation
	}

	UmsResourcePagination struct {
		Data []*UmsResource
		UmsResourcePaginationBasic
	}

	UmsResourcePaginationBasic struct {
		CurrentPage int64
		PageSize    int64
		TotalCount  int64
		TotalPage   int64
	}
)

func newUmsResourceModel(db *gorm.DB) *defaultUmsResourceModel {
	return &defaultUmsResourceModel{
		table:   "`ums_resource`",
		ormConn: db,
	}
}

func (UmsResource) TableName() string {
	return "`ums_resource`"
}

func (m UmsResource) ToProto(toValue interface{}) error {
	return copier.Copy(toValue, &m)
}

func (m *defaultUmsResourceModel) Delete(ctx context.Context, id int64) error {
	return m.OrmSession(ctx).Delete(&UmsResource{}, id).Error
}

func (m *defaultUmsResourceModel) FindOne(ctx context.Context, id int64, preloadList ...string) (*UmsResource, error) {
	var mm UmsResource
	db := m.OrmSession(ctx)
	for _, preload := range preloadList {
		db = db.Preload(preload)
	}
	err := db.First(&mm, id).Error
	switch err {
	case nil:
		return &mm, nil
	case gorm.ErrRecordNotFound:
		return nil, gorm.ErrRecordNotFound
	default:
		return nil, err
	}
}

func (m *defaultUmsResourceModel) OrmSession(ctx context.Context) *gorm.DB {
	return m.ormConn.Model(&UmsResource{}).WithContext(ctx)
}

func (m *defaultUmsResourceModel) Transaction(ctx context.Context, fc func(tx *gorm.DB) error, opts ...*sql.TxOptions) error {
	return m.ormConn.WithContext(ctx).Transaction(fc, opts...)
}

func (m *defaultUmsResourceModel) FindPageListByBuilder(db *gorm.DB, page, pageSize int64) (*UmsResourcePagination, error) {
	// 总行数
	var totalCount int64
	if err := db.Count(&totalCount).Error; err != nil {
		return nil, err
	}
	// 总页数
	totalPage := int64(math.Ceil(float64(totalCount) / float64(pageSize)))

	resp := new(UmsResourcePagination)
	resp.PageSize = pageSize
	resp.TotalPage = totalPage
	resp.CurrentPage = page
	resp.TotalCount = totalCount

	// 没有数据则返回空数据
	if totalCount <= 0 {
		return resp, nil
	}
	// 当前页数没有数据也返回空数据
	if totalCount < ((page - 1) * pageSize) {
		return resp, nil
	}

	offset := int((page - 1) * pageSize)
	if err := db.Offset(offset).Limit(int(pageSize)).Find(&resp.Data).Error; err != nil {
		return nil, err
	}

	return resp, nil
}

func (m UmsResourcePagination) Pagination() UmsResourcePaginationBasic {
	return UmsResourcePaginationBasic{
		CurrentPage: m.CurrentPage,
		PageSize:    m.PageSize,
		TotalPage:   m.TotalPage,
		TotalCount:  m.TotalCount,
	}
}

func (m UmsResourcePagination) ToProto(to any, toData any, toPagination any) error {
	if to != nil {
		if err := copier.CopyWithOption(to, m, copier.Option{}); err != nil {
			return err
		}
	}
	if toData != nil {
		if err := copier.Copy(toData, m.Data); err != nil {
			return err
		}
	}
	if toPagination != nil {
		if err := copier.Copy(toPagination, m.Pagination()); err != nil {
			return err
		}
	}
	return nil
}

func (m *defaultUmsResourceModel) Insert(ctx context.Context, data *UmsResource) error {
	return m.OrmSession(ctx).Create(data).Error
}

func (m *defaultUmsResourceModel) Update(ctx context.Context, data *UmsResource) error {
	if data.Id <= 0 {
		return gorm.ErrMissingWhereClause
	}
	return m.OrmSession(ctx).Where("id = ?", data.Id).Save(data).Error
}
