// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"math"

	"fmt"
	"github.com/jinzhu/copier"
	"gorm.io/gorm"
)

var (
	_ sql.IsolationLevel
)

type (
	umsRoleResourceRelationModel interface {
		Insert(ctx context.Context, data *UmsRoleResourceRelation) error
		FindOne(ctx context.Context, id int64, preloadList ...string) (*UmsRoleResourceRelation, error)
		OrmSession(ctx context.Context) *gorm.DB
		Transaction(ctx context.Context, fc func(tx *gorm.DB) error, opts ...*sql.TxOptions) error
		FindPageListByBuilder(ormSession *gorm.DB, keyword *KeywordUmsRoleResourceRelationModel) (*UmsRoleResourceRelationPagination, error)
		Update(ctx context.Context, data *UmsRoleResourceRelation) error
		Delete(ctx context.Context, id int64) error
	}

	defaultUmsRoleResourceRelationModel struct {
		table   string
		ormConn *gorm.DB
	}

	UmsRoleResourceRelation struct {
		Id         int64         `json:"id" gorm:"primary_key"`
		RoleId     sql.NullInt64 `json:"role_id"`     // 角色ID
		ResourceId sql.NullInt64 `json:"resource_id"` // 资源ID
		UmsRoleResourceRelationRelation
	}

	UmsRoleResourceRelationPagination struct {
		Data []*UmsRoleResourceRelation
		UmsRoleResourceRelationPaginationBasic
	}

	UmsRoleResourceRelationPaginationBasic struct {
		CurrentPage int64
		PageSize    int64
		TotalCount  int64
		TotalPage   int64
	}

	KeywordUmsRoleResourceRelationModel struct {
		KeywordKey     string //like 关键字
		KeywordValue   string //like 值
		Page, PageSize int64
	}
)

func newUmsRoleResourceRelationModel(db *gorm.DB) *defaultUmsRoleResourceRelationModel {
	return &defaultUmsRoleResourceRelationModel{
		table:   "`ums_role_resource_relation`",
		ormConn: db,
	}
}

func (UmsRoleResourceRelation) TableName() string {
	return "`ums_role_resource_relation`"
}

func (m UmsRoleResourceRelation) ToProto(toValue interface{}) error {
	return copier.Copy(toValue, &m)
}

func (m *defaultUmsRoleResourceRelationModel) Delete(ctx context.Context, id int64) error {
	return m.OrmSession(ctx).Delete(&UmsRoleResourceRelation{}, id).Error
}

func (m *defaultUmsRoleResourceRelationModel) FindOne(ctx context.Context, id int64, preloadList ...string) (*UmsRoleResourceRelation, error) {
	var mm UmsRoleResourceRelation
	db := m.OrmSession(ctx)
	for _, preload := range preloadList {
		db = db.Preload(preload)
	}
	err := db.First(&mm, id).Error
	switch err {
	case nil:
		return &mm, nil
	case gorm.ErrRecordNotFound:
		return nil, gorm.ErrRecordNotFound
	default:
		return nil, err
	}
}

func (m *defaultUmsRoleResourceRelationModel) OrmSession(ctx context.Context) *gorm.DB {
	return m.ormConn.Model(&UmsRoleResourceRelation{}).WithContext(ctx)
}

func (m *defaultUmsRoleResourceRelationModel) Transaction(ctx context.Context, fc func(tx *gorm.DB) error, opts ...*sql.TxOptions) error {
	return m.ormConn.WithContext(ctx).Transaction(fc, opts...)
}

func (m *defaultUmsRoleResourceRelationModel) FindPageListByBuilder(db *gorm.DB, keyword *KeywordUmsRoleResourceRelationModel) (*UmsRoleResourceRelationPagination, error) {
	page := keyword.Page
	pageSize := keyword.PageSize
	// 总行数
	var totalCount int64
	if err := db.Count(&totalCount).Error; err != nil {
		return nil, err
	}
	// 总页数
	totalPage := int64(math.Ceil(float64(totalCount) / float64(pageSize)))

	resp := new(UmsRoleResourceRelationPagination)
	resp.PageSize = pageSize
	resp.TotalPage = totalPage
	resp.CurrentPage = page
	resp.TotalCount = totalCount

	// 没有数据则返回空数据
	if totalCount <= 0 {
		return resp, nil
	}
	// 当前页数没有数据也返回空数据
	if totalCount < ((page - 1) * pageSize) {
		return resp, nil
	}
	if keyword.KeywordKey != "" && keyword.KeywordValue != "" {
		db = db.Where(fmt.Sprintf("%s = ?", keyword.KeywordKey), keyword.KeywordValue)
	}
	offset := int((page - 1) * pageSize)
	if err := db.Offset(offset).Limit(int(pageSize)).Find(&resp.Data).Error; err != nil {
		return nil, err
	}

	return resp, nil
}

func (m UmsRoleResourceRelationPagination) Pagination() UmsRoleResourceRelationPaginationBasic {
	return UmsRoleResourceRelationPaginationBasic{
		CurrentPage: m.CurrentPage,
		PageSize:    m.PageSize,
		TotalPage:   m.TotalPage,
		TotalCount:  m.TotalCount,
	}
}

func (m UmsRoleResourceRelationPagination) ToProto(to any, toData any, toPagination any) error {
	if to != nil {
		if err := copier.CopyWithOption(to, m, copier.Option{}); err != nil {
			return err
		}
	}
	if toData != nil {
		if err := copier.Copy(toData, m.Data); err != nil {
			return err
		}
	}
	if toPagination != nil {
		if err := copier.Copy(toPagination, m.Pagination()); err != nil {
			return err
		}
	}
	return nil
}

func (m *defaultUmsRoleResourceRelationModel) Insert(ctx context.Context, data *UmsRoleResourceRelation) error {
	return m.OrmSession(ctx).Create(data).Error
}

func (m *defaultUmsRoleResourceRelationModel) Update(ctx context.Context, data *UmsRoleResourceRelation) error {
	if data.Id <= 0 {
		return gorm.ErrMissingWhereClause
	}
	return m.OrmSession(ctx).Where("id = ?", data.Id).Save(data).Error
}
