// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	admin "github.com/yunbaifan/go-mall/admin/internal/handler/admin"
	"github.com/yunbaifan/go-mall/admin/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: admin.AdminLoginHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/admin"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JWTAuthToken},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/info",
					Handler: admin.AdminInfoHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/logout",
					Handler: admin.AdminLogoutHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/refreshToken",
					Handler: admin.RefreshTokenHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/register",
					Handler: admin.AdminRegisterHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin"),
	)
}
