// Code generated by goctl. DO NOT EDIT.
package types

type AdminCountResponse struct {
	Count int64 `json:"count" description:"更新数量"`
}

type AdminGetItemRequest struct {
	UserID int64 `path:"userId" description:"用户ID" validate:"required"`
}

type AdminInfo struct {
	Roles []string `json:"roles" default:"[]" description:"角色列表"`
	Icon  string   `json:"icon" default:"" description:"头像"`
	Menus []Menus  `json:"menus" default:"[]" description:"菜单列表"`
}

type AdminListRequest struct {
	Keyword  string `json:"keyword" description:"关键字" validate:"omitempty"`
	PageSize int64  `json:"pageSize" description:"每页数量" validate:"required,default=10"`
	PageNum  int64  `json:"pageNum" description:"页码" validate:"required,default=1"`
}

type AdminListResponse struct {
	Total     int64           `json:"total" description:"总数"`
	List      []AdminResponse `json:"list" description:"列表"`
	PageNum   int64           `json:"pageNum" description:"页码"`
	PageSize  int64           `json:"pageSize" description:"每页数量"`
	TotalPage int64           `json:"totalPage" description:"总页数"`
}

type AdminResponse struct {
	ID         int64  `json:"id" description:"ID"`
	Username   string `json:"username" description:"用户名"`
	Password   string `json:"password" description:"密码"`
	Icon       string `json:"icon" description:"头像"`
	Email      string `json:"email" description:"邮箱"`
	NickName   string `json:"nickName" description:"昵称"`
	Note       string `json:"note" description:"备注"`
	CreateTime string `json:"createTime" description:"创建时间"`
	LoginTime  string `json:"loginTime" description:"登录时间"`
	Status     int64  `json:"status" description:"状态"`
}

type AdminRoleListRequest struct {
	AdminId int64 `path:"adminId" description:"用户ID" validate:"required"`
}

type AdminRoleListResponse struct {
	Id          int64  `json:"id" description:"ID"`
	Name        string `json:"name" description:"名称"`
	Description string `json:"description" description:"描述"`
	AdminCount  int64  `json:"adminCount" description:"用户数量"`
	CreateTime  string `json:"createTime" description:"创建时间"`
	Status      int64  `json:"status" description:"状态"`
	Sort        int64  `json:"sort" description:"排序"`
}

type AdminRoleUpdateRequest struct {
	AdminId int64  `json:"adminId" description:"用户ID" validate:"required"`
	RoleIDs string `json:"roleIds" description:"角色ID列表" validate:"required"`
}

type LoginRequest struct {
	Username string `validate:"required, min=6, max=20" json:"username" description:"用户名"`
	Password string `validate:"required, min=6, max=20" json:"password" description:"密码"`
}

type LoginResponse struct {
	Token     string `json:"token" description:"token"`
	TokenHead string `json:"tokenHead" description:"token头"`
}

type Menus struct {
	Id         int    `json:"id" description:"菜单ID"`
	ParentId   int    `json:"parentId" description:"父级ID"`
	CreateTime string `json:"createTime" description:"创建时间"`
	Level      int    `json:"level" description:"层级"`
	Name       string `json:"name" description:"菜单名称"`
	Sort       int    `json:"sort" description:"排序"`
	Icon       string `json:"icon" description:"图标"`
	Hidden     bool   `json:"hidden" description:"是否隐藏"`
}

type RegisterRequest struct {
	Username string `json:"username" description:"用户名" validate:"required"`
	Password string `json:"password" description:"密码" validate:"required,min=6,max=20"`
	Email    string `json:"email" description:"邮箱" validate:"required,email"`
	NickName string `json:"nickName" description:"昵称" validate:"required,max=20"`
	Note     string `json:"note" description:"备注" validate:"max=100"`
	Status   int64  `json:"status" description:"状态" validate:"required,default=0"`
}

type Request struct {
	Name string `path:"name,options=you|me"`
}

type RoleCountResponse struct {
	Count int64 `json:"count" description:"更新数量"`
}

type RoleDeleteRequest struct {
	Id int `json:"id" validate:"required"`
}

type RoleListRequest struct {
	Page     int `validate:"required" default:"1" form:"page"`
	PageSize int `validate:"required" form:"pageSize" default:"10"`
}

type RoleRequest struct {
	Id          int    `json:"id" validate:"required"`
	Name        string `json:"name" validate:"required,min=6,max=32"`
	Description string `json:"description" validate:"required,min=6,max=64"`
	AdminCount  int    `json:"adminCount" validate:"required" default:"0"`
	Status      int    `json:"status" validate:"required" default:"1"`
}

type UpdatePasswordRequest struct {
	UserID      int64  `json:"userId" description:"用户ID" validate:"required"`
	OldPassword string `json:"oldPassword" description:"旧密码" validate:"required"`
	NewPassword string `json:"newPassword" description:"新密码" validate:"required"`
}
